{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "```\r\n>>> import gmt\r\nTraceback (most recent call last):\r\n  File \"/users1j/cliu/soft/anaconda2/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/utils.py\", line 159, in load_libgmt\r\n    libgmt = ctypes.CDLL('.'.join([libname, clib_extension()]))\r\n  File \"/users1j/cliu/soft/anaconda2/envs/gmt-python/lib/python3.6/ctypes/__init__.py\", line 348, in __init__\r\n    self._handle = _dlopen(self._name, mode)\r\nOSError: libpoppler.so.71: cannot open shared object file: No such file or directory\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/users1j/cliu/soft/anaconda2/envs/gmt-python/lib/python3.6/site-packages/gmt/__init__.py\", line 27, in <module>\r\n    _begin()\r\n  File \"/users1j/cliu/soft/anaconda2/envs/gmt-python/lib/python3.6/site-packages/gmt/session_management.py\", line 17, in begin\r\n    with LibGMT() as lib:\r\n  File \"/users1j/cliu/soft/anaconda2/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py\", line 103, in __init__\r\n    self._bind_clib_functions(libname)\r\n  File \"/users1j/cliu/soft/anaconda2/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py\", line 136, in _bind_clib_functions\r\n    self._libgmt = load_libgmt(libname)\r\n  File \"/users1j/cliu/soft/anaconda2/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/utils.py\", line 168, in load_libgmt\r\n    raise GMTCLibNotFoundError(msg)\r\ngmt.exceptions.GMTCLibNotFoundError: Couldn't find the GMT shared library 'libgmt'. Have you tried setting the LD_LIBRARY_PATH environment variable?\r\nOriginal error message:\r\n\r\n    libpoppler.so.71: cannot open shared object file: No such file or directory\r\n```\r\n  ",
    "closed_at": "2018-03-07T23:17:10Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
        "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
        "followers_url": "https://api.github.com/users/leouieda/followers",
        "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
        "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/leouieda",
        "id": 290082,
        "login": "leouieda",
        "node_id": "MDQ6VXNlcjI5MDA4Mg==",
        "organizations_url": "https://api.github.com/users/leouieda/orgs",
        "received_events_url": "https://api.github.com/users/leouieda/received_events",
        "repos_url": "https://api.github.com/users/leouieda/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/leouieda"
    },
    "comments": 19,
    "comments_content": [
        {
            "author_association": "NONE",
            "body": "I change the   LD_LIBRARY_PATH. It can be imported now,but it does not work",
            "created_at": "2018-01-01T10:05:33Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-354645877",
            "id": 354645877,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM1NDY0NTg3Nw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/354645877/reactions"
            },
            "updated_at": "2018-01-01T10:05:33Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/354645877",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/22513019?v=4",
                "events_url": "https://api.github.com/users/xigrug/events{/privacy}",
                "followers_url": "https://api.github.com/users/xigrug/followers",
                "following_url": "https://api.github.com/users/xigrug/following{/other_user}",
                "gists_url": "https://api.github.com/users/xigrug/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/xigrug",
                "id": 22513019,
                "login": "xigrug",
                "node_id": "MDQ6VXNlcjIyNTEzMDE5",
                "organizations_url": "https://api.github.com/users/xigrug/orgs",
                "received_events_url": "https://api.github.com/users/xigrug/received_events",
                "repos_url": "https://api.github.com/users/xigrug/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/xigrug/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/xigrug/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/xigrug"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Hi @xigrug thinks seems to be a problem with a GDAL dependency (https://github.com/conda-forge/osmnx-feedstock/issues/23). Can you try deleting your environment and reinstalling everything? It might have been fixed already. If not, please report back.",
            "created_at": "2018-01-09T19:32:05Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-356389379",
            "id": 356389379,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM1NjM4OTM3OQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/356389379/reactions"
            },
            "updated_at": "2018-01-09T19:32:05Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/356389379",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "NONE",
            "body": "I have the same problem on my end. Fresh install. \r\n\r\nHere is the output:\r\n```Python\r\n>>> import gmt\r\nTraceback (most recent call last):\r\n  File \"/Users/adamprice/anaconda/envs/gmtpy/lib/python3.6/site-packages/gmt/clib/utils.py\", line 159, in load_libgmt\r\n    libgmt = ctypes.CDLL('.'.join([libname, clib_extension()]))\r\n  File \"/Users/adamprice/anaconda/envs/gmtpy/lib/python3.6/ctypes/__init__.py\", line 348, in __init__\r\n    self._handle = _dlopen(self._name, mode)\r\nOSError: dlopen(libgmt.dylib, 6): Library not loaded: @rpath/libpoppler.71.dylib\r\n  Referenced from: /Users/adamprice/anaconda/envs/gmtpy/lib/libgdal.20.dylib\r\n  Reason: image not found\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/Users/adamprice/anaconda/envs/gmtpy/lib/python3.6/site-packages/gmt/__init__.py\", line 28, in <module>\r\n    _begin()\r\n  File \"/Users/adamprice/anaconda/envs/gmtpy/lib/python3.6/site-packages/gmt/session_management.py\", line 17, in begin\r\n    with LibGMT() as lib:\r\n  File \"/Users/adamprice/anaconda/envs/gmtpy/lib/python3.6/site-packages/gmt/clib/core.py\", line 103, in __init__\r\n    self._bind_clib_functions(libname)\r\n  File \"/Users/adamprice/anaconda/envs/gmtpy/lib/python3.6/site-packages/gmt/clib/core.py\", line 136, in _bind_clib_functions\r\n    self._libgmt = load_libgmt(libname)\r\n  File \"/Users/adamprice/anaconda/envs/gmtpy/lib/python3.6/site-packages/gmt/clib/utils.py\", line 168, in load_libgmt\r\n    raise GMTCLibNotFoundError(msg)\r\ngmt.exceptions.GMTCLibNotFoundError: Couldn't find the GMT shared library 'libgmt'. Have you tried setting the LD_LIBRARY_PATH environment variable? \r\nOriginal error message: \r\n\r\n    dlopen(libgmt.dylib, 6): Library not loaded: @rpath/libpoppler.71.dylib\r\n  Referenced from: /Users/adamprice/anaconda/envs/gmtpy/lib/libgdal.20.dylib\r\n  Reason: image not found\r\n```",
            "created_at": "2018-02-25T00:55:58Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-368273229",
            "id": 368273229,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM2ODI3MzIyOQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/368273229/reactions"
            },
            "updated_at": "2018-02-25T00:57:57Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/368273229",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/29460883?v=4",
                "events_url": "https://api.github.com/users/adamnicholasprice/events{/privacy}",
                "followers_url": "https://api.github.com/users/adamnicholasprice/followers",
                "following_url": "https://api.github.com/users/adamnicholasprice/following{/other_user}",
                "gists_url": "https://api.github.com/users/adamnicholasprice/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/adamnicholasprice",
                "id": 29460883,
                "login": "adamnicholasprice",
                "node_id": "MDQ6VXNlcjI5NDYwODgz",
                "organizations_url": "https://api.github.com/users/adamnicholasprice/orgs",
                "received_events_url": "https://api.github.com/users/adamnicholasprice/received_events",
                "repos_url": "https://api.github.com/users/adamnicholasprice/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/adamnicholasprice/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/adamnicholasprice/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/adamnicholasprice"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@adamnicholasprice thanks for reporting the issue.\r\n\r\nDid you follow the instructions in http://www.gmtpython.xyz/install.html for installing in a conda environment? If so, could you please post the output of `conda list`?\r\n",
            "created_at": "2018-02-26T20:38:19Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-368641872",
            "id": 368641872,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM2ODY0MTg3Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 1,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/368641872/reactions"
            },
            "updated_at": "2018-02-26T20:38:19Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/368641872",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "NONE",
            "body": "Yes I followed the install instructions (even cloned the git on the second time install).\r\n\r\n```Unix\r\n(gmt-python)adamprice$ conda list\r\n# packages in environment at /Users/adamprice/anaconda/envs/gmt-python:\r\n#\r\n# Name                    Version                   Build  Channel\r\nappnope                   0.1.0                    py36_0    conda-forge\r\nattrs                     17.4.0                     py_0    conda-forge\r\nbackports                 1.0                      py36_1    conda-forge\r\nbackports.functools_lru_cache 1.5                      py36_0    conda-forge\r\nblas                      1.1                    openblas    conda-forge\r\nboost                     1.66.0                   py36_1    conda-forge\r\nboost-cpp                 1.66.0                        1    conda-forge\r\nbzip2                     1.0.6                         1    conda-forge\r\nca-certificates           2018.1.18                     0    conda-forge\r\ncairo                     1.14.10                       0    conda-forge\r\ncertifi                   2018.1.18                py36_0    conda-forge\r\ncurl                      7.55.1                        0    conda-forge\r\ncycler                    0.10.0                   py36_0    conda-forge\r\ndcw-gmt                   1.1.2                         0    conda-forge\r\ndecorator                 4.1.2                    py36_0    conda-forge\r\nexpat                     2.2.5                         0    conda-forge\r\nfftw                      3.3.7                         0    conda-forge\r\nfontconfig                2.12.6                        0    conda-forge\r\nfreetype                  2.8.1                         0    conda-forge\r\nfreexl                    1.0.4                         0    conda-forge\r\ngdal                      2.2.2            py36hd505dc6_1  \r\ngeos                      3.6.2                         1    conda-forge\r\ngettext                   0.19.8.1                      0    conda-forge\r\nghostscript               9.22                          0    conda-forge\r\ngiflib                    5.1.4                         0    conda-forge\r\nglib                      2.55.0                        0    conda-forge\r\ngmt                       6.0.0a12        blas_openblas_201  [blas_openblas]  conda-forge/label/dev\r\ngmt-python                0.1a3+61.gdfb0720           <pip>\r\ngshhg-gmt                 2.3.7                         0    conda-forge\r\nhdf4                      4.2.13                        0    conda-forge\r\nhdf5                      1.10.1                        2    conda-forge\r\nicu                       58.2                          0    conda-forge\r\nipython                   6.2.1                    py36_1    conda-forge\r\nipython_genutils          0.2.0                    py36_0    conda-forge\r\njedi                      0.11.1                   py36_0    conda-forge\r\njpeg                      9b                            2    conda-forge\r\njson-c                    0.12.1                        0    conda-forge\r\nkealib                    1.4.7                         4    conda-forge\r\nkrb5                      1.14.2                        0    conda-forge\r\nlibcxx                    4.0.1                h579ed51_0  \r\nlibcxxabi                 4.0.1                hebd6815_0  \r\nlibdap4                   3.19.2                        1    conda-forge\r\nlibedit                   3.1                  hb4e282d_0  \r\nlibffi                    3.2.1                h475c297_4  \r\nlibgdal                   2.2.2                h3559a57_1  \r\nlibgfortran               3.0.0                         0    conda-forge\r\nlibiconv                  1.15                          0    conda-forge\r\nlibkml                    1.3.0                         6    conda-forge\r\nlibnetcdf                 4.4.1.1                      10    conda-forge\r\nlibpng                    1.6.34                        0    conda-forge\r\nlibpq                     9.6.6                h77f6c7a_0  \r\nlibspatialite             4.3.0a              h0a2fa02_18  \r\nlibssh2                   1.8.0                         2    conda-forge\r\nlibtiff                   4.0.9                         0    conda-forge\r\nlibxml2                   2.9.7                         0    conda-forge\r\nmatplotlib                2.1.2                    py36_0    conda-forge\r\nncurses                   6.0                  hd04f020_2  \r\nnose                      1.3.7                    py36_2    conda-forge\r\nnumpy                     1.14.1          py36_blas_openblas_200  [blas_openblas]  conda-forge\r\nopenblas                  0.2.20                        7    conda-forge\r\nopenjpeg                  2.3.0                         2    conda-forge\r\nopenssl                   1.0.2n                        0    conda-forge\r\npandas                    0.22.0                   py36_0    conda-forge\r\nparso                     0.1.1                      py_0    conda-forge\r\npcre                      8.39                          0    conda-forge\r\npexpect                   4.4.0                    py36_0    conda-forge\r\npickleshare               0.7.4                    py36_0    conda-forge\r\npip                       9.0.1            py36h1555ced_4  \r\npixman                    0.34.0                        1    conda-forge\r\npluggy                    0.6.0                      py_0    conda-forge\r\npoppler                   0.61.1                        3    conda-forge\r\npoppler-data              0.4.8                         0    conda-forge\r\nproj4                     4.9.3                         5    conda-forge\r\nprompt_toolkit            1.0.15                   py36_0    conda-forge\r\nptyprocess                0.5.2                    py36_0    conda-forge\r\npy                        1.5.2                      py_0    conda-forge\r\npygments                  2.2.0                    py36_0    conda-forge\r\npyparsing                 2.2.0                    py36_0    conda-forge\r\npytest                    3.4.1                    py36_0    conda-forge\r\npytest-mpl                0.9                        py_0    conda-forge\r\npython                    3.6.4                hc167b69_1  \r\npython-dateutil           2.6.1                    py36_0    conda-forge\r\npytz                      2018.3                     py_0    conda-forge\r\nreadline                  7.0                  hc1231fa_4  \r\nsetuptools                38.5.1                   py36_0  \r\nsimplegeneric             0.8.1                    py36_0    conda-forge\r\nsix                       1.11.0                   py36_1    conda-forge\r\nsqlite                    3.22.0               h3efe00b_0  \r\ntk                        8.6.7                h35a86e2_3  \r\ntornado                   4.5.3                    py36_0    conda-forge\r\ntraitlets                 4.3.2                    py36_0    conda-forge\r\nwcwidth                   0.1.7                    py36_0    conda-forge\r\nwheel                     0.30.0           py36h5eb2c71_1  \r\nxerces-c                  3.2.0                         0    conda-forge\r\nxz                        5.2.3                h0278029_2  \r\nzlib                      1.2.11               hf3cbc9b_2 \r\n```",
            "created_at": "2018-02-26T20:40:48Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-368642583",
            "id": 368642583,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM2ODY0MjU4Mw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/368642583/reactions"
            },
            "updated_at": "2018-02-26T20:41:22Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/368642583",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/29460883?v=4",
                "events_url": "https://api.github.com/users/adamnicholasprice/events{/privacy}",
                "followers_url": "https://api.github.com/users/adamnicholasprice/followers",
                "following_url": "https://api.github.com/users/adamnicholasprice/following{/other_user}",
                "gists_url": "https://api.github.com/users/adamnicholasprice/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/adamnicholasprice",
                "id": 29460883,
                "login": "adamnicholasprice",
                "node_id": "MDQ6VXNlcjI5NDYwODgz",
                "organizations_url": "https://api.github.com/users/adamnicholasprice/orgs",
                "received_events_url": "https://api.github.com/users/adamnicholasprice/received_events",
                "repos_url": "https://api.github.com/users/adamnicholasprice/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/adamnicholasprice/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/adamnicholasprice/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/adamnicholasprice"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@adamnicholasprice thanks! I think I see a problem. Your gdal isn't coming from conda-forge for some reason but poppler is. That might be causing the linking issue. Could you try the following please?\r\n\r\n1. Delete the gmt-python environment: \r\n```\r\nconda env remove --name gmt-python\r\n```\r\n2. Create (or edit) a `.condarc` file in your home directory to include this (it will make conda-forge a priority):\r\n```\r\nchannels:\r\n  - conda-forge\r\n  - defaults\r\n```\r\n3. Repeat the install process. If things don't work, check `conda list` to see if `gdal` is coming from the `conda-forge` channel and report back.\r\n\r\nMore information about these issues on the conda-forge documentation: https://conda-forge.org/docs/conda-forge_gotchas.html",
            "created_at": "2018-02-27T00:01:47Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-368695742",
            "id": 368695742,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM2ODY5NTc0Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 3,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 3,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/368695742/reactions"
            },
            "updated_at": "2018-02-27T00:02:23Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/368695742",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "NONE",
            "body": "@leouieda That did not work for me but I was able to resolve it using the instructions in https://github.com/conda-forge/gdal-feedstock .  Looking forward to using the package!",
            "created_at": "2018-02-27T00:39:29Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-368703828",
            "id": 368703828,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM2ODcwMzgyOA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/368703828/reactions"
            },
            "updated_at": "2018-02-27T00:39:29Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/368703828",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/29460883?v=4",
                "events_url": "https://api.github.com/users/adamnicholasprice/events{/privacy}",
                "followers_url": "https://api.github.com/users/adamnicholasprice/followers",
                "following_url": "https://api.github.com/users/adamnicholasprice/following{/other_user}",
                "gists_url": "https://api.github.com/users/adamnicholasprice/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/adamnicholasprice",
                "id": 29460883,
                "login": "adamnicholasprice",
                "node_id": "MDQ6VXNlcjI5NDYwODgz",
                "organizations_url": "https://api.github.com/users/adamnicholasprice/orgs",
                "received_events_url": "https://api.github.com/users/adamnicholasprice/received_events",
                "repos_url": "https://api.github.com/users/adamnicholasprice/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/adamnicholasprice/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/adamnicholasprice/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/adamnicholasprice"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I'm glad it's working! Would you mind sharing what you did so that we can have it as a reference?\r\n\r\nAlso, did you check if your gdal is now coming from conda-forge?",
            "created_at": "2018-02-27T01:28:40Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-368713854",
            "id": 368713854,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM2ODcxMzg1NA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/368713854/reactions"
            },
            "updated_at": "2018-02-27T01:28:40Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/368713854",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "NONE",
            "body": "This is the line of syntax seemed to have fixed by issue.\r\n```\r\nsource activate [env-name]\r\nconda config --add channels conda-forge\r\nconda install gdal\r\n```\r\nAfter which run the \r\n```\r\nconda list\r\n```\r\ncommand to make sure packages are coming from conda-forge",
            "created_at": "2018-03-01T17:40:21Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-369670468",
            "id": 369670468,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM2OTY3MDQ2OA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 10,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 1,
                "laugh": 2,
                "rocket": 1,
                "total_count": 14,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/369670468/reactions"
            },
            "updated_at": "2018-03-01T17:40:21Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/369670468",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/29460883?v=4",
                "events_url": "https://api.github.com/users/adamnicholasprice/events{/privacy}",
                "followers_url": "https://api.github.com/users/adamnicholasprice/followers",
                "following_url": "https://api.github.com/users/adamnicholasprice/following{/other_user}",
                "gists_url": "https://api.github.com/users/adamnicholasprice/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/adamnicholasprice",
                "id": 29460883,
                "login": "adamnicholasprice",
                "node_id": "MDQ6VXNlcjI5NDYwODgz",
                "organizations_url": "https://api.github.com/users/adamnicholasprice/orgs",
                "received_events_url": "https://api.github.com/users/adamnicholasprice/received_events",
                "repos_url": "https://api.github.com/users/adamnicholasprice/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/adamnicholasprice/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/adamnicholasprice/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/adamnicholasprice"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "I had the same issue this morning. @adamnicholasprice solution also worked for me. Thanks!",
            "created_at": "2018-03-07T18:56:36Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-371245314",
            "id": 371245314,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM3MTI0NTMxNA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/371245314/reactions"
            },
            "updated_at": "2018-03-07T18:56:36Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/371245314",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/8233693?v=4",
                "events_url": "https://api.github.com/users/btozer/events{/privacy}",
                "followers_url": "https://api.github.com/users/btozer/followers",
                "following_url": "https://api.github.com/users/btozer/following{/other_user}",
                "gists_url": "https://api.github.com/users/btozer/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/btozer",
                "id": 8233693,
                "login": "btozer",
                "node_id": "MDQ6VXNlcjgyMzM2OTM=",
                "organizations_url": "https://api.github.com/users/btozer/orgs",
                "received_events_url": "https://api.github.com/users/btozer/received_events",
                "repos_url": "https://api.github.com/users/btozer/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/btozer/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/btozer/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/btozer"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@btozer thanks for reporting. I'll add these instructions to the documentation.",
            "created_at": "2018-03-07T22:43:06Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-371311915",
            "id": 371311915,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM3MTMxMTkxNQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/371311915/reactions"
            },
            "updated_at": "2018-03-07T22:43:06Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/371311915",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I've updated the install instructions to reflect the solution by @adamnicholasprice: http://www.gmtpython.xyz/install.html#installing-gmt-and-other-dependencies\r\n\r\nCould anyone please give it a try to see if it works in machines other than mine?",
            "created_at": "2018-03-07T23:20:09Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-371321002",
            "id": 371321002,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM3MTMyMTAwMg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/371321002/reactions"
            },
            "updated_at": "2018-03-07T23:20:16Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/371321002",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hi, I'm very new to Python and Anaconda and tried to reproduce the mentioned steps, but sadly the error still occur:\r\n\r\n```\r\nrunfile('/media/mattes/data1/dataDMattes/Code/Python/PythonProgram/main.py', wdir='/media/mattes/data1/dataDMattes/Code/Python/PythonProgram')\r\nTraceback (most recent call last):\r\n\r\n  File \"<ipython-input-1-e8fdc416f3c8>\", line 1, in <module>\r\n    runfile('/media/mattes/data1/dataDMattes/Code/Python/PythonProgram/main.py', wdir='/media/mattes/data1/dataDMattes/Code/Python/PythonProgram')\r\n\r\n  File \"/home/mattes/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py\", line 705, in runfile\r\n    execfile(filename, namespace)\r\n\r\n  File \"/home/mattes/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py\", line 102, in execfile\r\n    exec(compile(f.read(), filename, 'exec'), namespace)\r\n\r\n  File \"/media/mattes/data1/dataDMattes/Code/Python/PythonProgram/main.py\", line 16, in <module>\r\n    import ogr\r\n\r\n  File \"/home/mattes/anaconda3/lib/python3.6/site-packages/ogr.py\", line 2, in <module>\r\n    from osgeo.gdal import deprecation_warn\r\n\r\n  File \"/home/mattes/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py\", line 21, in <module>\r\n    _gdal = swig_import_helper()\r\n\r\n  File \"/home/mattes/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py\", line 17, in swig_import_helper\r\n    _mod = imp.load_module('_gdal', fp, pathname, description)\r\n\r\n  File \"/home/mattes/anaconda3/lib/python3.6/imp.py\", line 243, in load_module\r\n    return load_dynamic(name, filename, file)\r\n\r\n  File \"/home/mattes/anaconda3/lib/python3.6/imp.py\", line 343, in load_dynamic\r\n    return _load(spec)\r\n\r\nImportError: /home/mattes/anaconda3/lib/python3.6/site-packages/osgeo/../../.././libkea.so.1.4: undefined symbol: _ZN2H56H5FileC1ERKSsjRKNS_17FileCreatPropListERKNS_15FileAccPropListE\r\n```\r\n\r\nThe output of my `conda list` is the following:\r\n```\r\n(gmt-python) mattes@gipc163:~$ conda list\r\n# packages in environment at /home/mattes/anaconda3/envs/gmt-python:\r\n#\r\n# Name                    Version                   Build  Channel\r\nblas                      1.1                    openblas    conda-forge\r\nboost                     1.66.0                   py36_1    conda-forge\r\nboost-cpp                 1.66.0                        1    conda-forge\r\nbzip2                     1.0.6                         1    conda-forge\r\nca-certificates           2018.4.16                     0    conda-forge\r\ncairo                     1.14.10                       0    conda-forge\r\ncertifi                   2018.4.16                py36_0    conda-forge\r\ncurl                      7.60.0                        0    conda-forge\r\ndcw-gmt                   1.1.3                         0    conda-forge\r\nexpat                     2.2.5                         0    conda-forge\r\nfftw                      3.3.7                         0    conda-forge\r\nfontconfig                2.12.6                        0    conda-forge\r\nfreetype                  2.8.1                         0    conda-forge\r\nfreexl                    1.0.5                         0    conda-forge\r\ngdal                      2.2.4                    py36_0    conda-forge\r\ngeos                      3.6.2                         1    conda-forge\r\ngeotiff                   1.4.2                         1    conda-forge\r\ngettext                   0.19.8.1                      0    conda-forge\r\nghostscript               9.22                          0    conda-forge\r\ngiflib                    5.1.4                         0    conda-forge\r\nglib                      2.55.0                        0    conda-forge\r\ngmt                       5.4.3           blas_openblas_202  [blas_openblas]  conda-forge\r\ngshhg-gmt                 2.3.7                         0    conda-forge\r\nhdf4                      4.2.13                        0    conda-forge\r\nhdf5                      1.10.1                        2    conda-forge\r\nicu                       58.2                          0    conda-forge\r\njpeg                      9b                            2    conda-forge\r\njson-c                    0.12.1                        0    conda-forge\r\nkealib                    1.4.7                         4    conda-forge\r\nkrb5                      1.14.6                        0    conda-forge\r\nlibdap4                   3.18.3                        2    conda-forge\r\nlibffi                    3.2.1                         3    conda-forge\r\nlibgdal                   2.2.4                         2    conda-forge\r\nlibgfortran               3.0.0                         1  \r\nlibiconv                  1.15                          0    conda-forge\r\nlibkml                    1.3.0                         6    conda-forge\r\nlibnetcdf                 4.6.1                         2    conda-forge\r\nlibpng                    1.6.34                        0    conda-forge\r\nlibpq                     9.6.3                         0    conda-forge\r\nlibspatialite             4.3.0a                       19    conda-forge\r\nlibssh2                   1.8.0                         2    conda-forge\r\nlibtiff                   4.0.9                         0    conda-forge\r\nlibxml2                   2.9.8                         0    conda-forge\r\nncurses                   5.9                          10    conda-forge\r\nnumpy                     1.14.3          py36_blas_openblas_200  [blas_openblas]  conda-forge\r\nopenblas                  0.2.20                        7    conda-forge\r\nopenjpeg                  2.3.0                         2    conda-forge\r\nopenssl                   1.0.2o                        0    conda-forge\r\npandas                    0.23.0                   py36_1    conda-forge\r\npcre                      8.41                          1    conda-forge\r\npip                       9.0.3                    py36_0    conda-forge\r\npixman                    0.34.0                        2    conda-forge\r\npoppler                   0.61.1                        3    conda-forge\r\npoppler-data              0.4.9                         0    conda-forge\r\nproj4                     4.9.3                         5    conda-forge\r\npython                    3.6.5                         1    conda-forge\r\npython-dateutil           2.7.3                      py_0    conda-forge\r\npytz                      2018.4                     py_0    conda-forge\r\nreadline                  7.0                           0    conda-forge\r\nsetuptools                39.2.0                   py36_0    conda-forge\r\nsix                       1.11.0                   py36_1    conda-forge\r\nsqlite                    3.20.1                        2    conda-forge\r\ntk                        8.6.7                         0    conda-forge\r\nutil-linux                2.21                          0  \r\nwheel                     0.31.0                   py36_0    conda-forge\r\nxerces-c                  3.2.0                         0    conda-forge\r\nxz                        5.2.3                         0    conda-forge\r\nzlib                      1.2.11                        0    conda-forge\r\n```",
            "created_at": "2018-05-25T08:42:14Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-391984548",
            "id": 391984548,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5MTk4NDU0OA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/391984548/reactions"
            },
            "updated_at": "2018-05-25T12:52:11Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/391984548",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/39593622?v=4",
                "events_url": "https://api.github.com/users/DennisScuba/events{/privacy}",
                "followers_url": "https://api.github.com/users/DennisScuba/followers",
                "following_url": "https://api.github.com/users/DennisScuba/following{/other_user}",
                "gists_url": "https://api.github.com/users/DennisScuba/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/DennisScuba",
                "id": 39593622,
                "login": "DennisScuba",
                "node_id": "MDQ6VXNlcjM5NTkzNjIy",
                "organizations_url": "https://api.github.com/users/DennisScuba/orgs",
                "received_events_url": "https://api.github.com/users/DennisScuba/received_events",
                "repos_url": "https://api.github.com/users/DennisScuba/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/DennisScuba/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/DennisScuba/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/DennisScuba"
            }
        },
        {
            "author_association": "NONE",
            "body": "@DennisScuba I've had the same issue as yours and ended up building a new conda env. ",
            "created_at": "2018-06-12T14:03:45Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-396601085",
            "id": 396601085,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5NjYwMTA4NQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 1,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/396601085/reactions"
            },
            "updated_at": "2018-06-12T14:03:45Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/396601085",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10216145?v=4",
                "events_url": "https://api.github.com/users/AloshkaD/events{/privacy}",
                "followers_url": "https://api.github.com/users/AloshkaD/followers",
                "following_url": "https://api.github.com/users/AloshkaD/following{/other_user}",
                "gists_url": "https://api.github.com/users/AloshkaD/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/AloshkaD",
                "id": 10216145,
                "login": "AloshkaD",
                "node_id": "MDQ6VXNlcjEwMjE2MTQ1",
                "organizations_url": "https://api.github.com/users/AloshkaD/orgs",
                "received_events_url": "https://api.github.com/users/AloshkaD/received_events",
                "repos_url": "https://api.github.com/users/AloshkaD/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/AloshkaD/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/AloshkaD/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/AloshkaD"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@DennisScuba and @AloshkaD yes, please use a separate environment for now. Also, notice that you have the wrong version of GMT (5.4.3 instead of 6.0.0).",
            "created_at": "2018-06-20T00:38:53Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-398587962",
            "id": 398587962,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5ODU4Nzk2Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/398587962/reactions"
            },
            "updated_at": "2018-06-20T00:38:53Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/398587962",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "NONE",
            "body": "I know this is closed but......I had a lot of problem recently with these issues. gmt would switch down to 5.4 when trying to work the conda-forge feedstock, having errors like @rpath/libpoppler.76.dylib\r\n  Referenced from: /anaconda3/envs/gmt-python/lib/libgdal.20.dylib. \r\n\r\nI checked my conda list and gdal was from the conda feedstock. But libgdal wasnt. So..\r\n\r\nconda install -c conda-forge libgdal\r\n\r\nThis worked.\r\n\r\nGreat program - Only thing with the install instructions I would say may help is to link/integrate the [install instructions ](https://www.gmtpython.xyz/latest/install.html) to the [feedstock instructions](https://github.com/conda-forge/gmt-feedstock) a little more. Just a bit of friendly feedback - feel free to ignore if Im being an idiot! I got a little confused - thanks :) \r\n",
            "created_at": "2018-10-22T00:52:06Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-431719002",
            "id": 431719002,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQzMTcxOTAwMg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 2,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/431719002/reactions"
            },
            "updated_at": "2018-10-22T00:52:06Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/431719002",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23740960?v=4",
                "events_url": "https://api.github.com/users/hammytheham/events{/privacy}",
                "followers_url": "https://api.github.com/users/hammytheham/followers",
                "following_url": "https://api.github.com/users/hammytheham/following{/other_user}",
                "gists_url": "https://api.github.com/users/hammytheham/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/hammytheham",
                "id": 23740960,
                "login": "hammytheham",
                "node_id": "MDQ6VXNlcjIzNzQwOTYw",
                "organizations_url": "https://api.github.com/users/hammytheham/orgs",
                "received_events_url": "https://api.github.com/users/hammytheham/received_events",
                "repos_url": "https://api.github.com/users/hammytheham/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/hammytheham/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/hammytheham/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/hammytheham"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Hi @hammytheham, thanks for the feedback!\r\n\r\n>  Just a bit of friendly feedback - feel free to ignore if Im being an idiot! I got a little confused - thanks :)\r\n\r\nNot at all! This has been a major problem from the start and a constant source of headaches for me :) Conda-forge is a relatively new resource and things are still a bit unstable. They have been doing a lot of work to get things better integrated with the default Anaconda. This will hopefully solve a large amount of these issues. I'm constantly tweaking this process but it's really hard to prepare for these errors since I don't get them.\r\n\r\nAlso, I really love to get contributions of this kind! The only way to have a robust set of install instructions is if people with diverse setups contribute to it. Would you like to try adding some words to the instructions? I would really appreciate it if you could help clarify what you found confusing and what eventually cleared things up.\r\n\r\nYou can do that online by going to https://github.com/GenericMappingTools/gmt-python/blob/master/doc/install.rst and clicking in the little pencil icon. ",
            "created_at": "2018-10-24T00:09:00Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-432465412",
            "id": 432465412,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQzMjQ2NTQxMg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/432465412/reactions"
            },
            "updated_at": "2018-10-24T00:09:00Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/432465412",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "NONE",
            "body": "Done :) ",
            "created_at": "2018-10-24T23:00:22Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-432856743",
            "id": 432856743,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQzMjg1Njc0Mw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/432856743/reactions"
            },
            "updated_at": "2018-10-24T23:00:22Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/432856743",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23740960?v=4",
                "events_url": "https://api.github.com/users/hammytheham/events{/privacy}",
                "followers_url": "https://api.github.com/users/hammytheham/followers",
                "following_url": "https://api.github.com/users/hammytheham/following{/other_user}",
                "gists_url": "https://api.github.com/users/hammytheham/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/hammytheham",
                "id": 23740960,
                "login": "hammytheham",
                "node_id": "MDQ6VXNlcjIzNzQwOTYw",
                "organizations_url": "https://api.github.com/users/hammytheham/orgs",
                "received_events_url": "https://api.github.com/users/hammytheham/received_events",
                "repos_url": "https://api.github.com/users/hammytheham/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/hammytheham/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/hammytheham/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/hammytheham"
            }
        },
        {
            "author_association": "NONE",
            "body": "I was having the same issue. so i opened anaconda navigator and go to the env. then in the channels, you can see default and conda-forge so you can **delete conda-forge**. then again install gdal, poppler. both will be available on default channel. this works for me",
            "created_at": "2019-03-16T17:15:43Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104#issuecomment-473566702",
            "id": 473566702,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ3MzU2NjcwMg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/473566702/reactions"
            },
            "updated_at": "2019-03-16T17:15:43Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/473566702",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35651955?v=4",
                "events_url": "https://api.github.com/users/prativadas/events{/privacy}",
                "followers_url": "https://api.github.com/users/prativadas/followers",
                "following_url": "https://api.github.com/users/prativadas/following{/other_user}",
                "gists_url": "https://api.github.com/users/prativadas/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/prativadas",
                "id": 35651955,
                "login": "prativadas",
                "node_id": "MDQ6VXNlcjM1NjUxOTU1",
                "organizations_url": "https://api.github.com/users/prativadas/orgs",
                "received_events_url": "https://api.github.com/users/prativadas/received_events",
                "repos_url": "https://api.github.com/users/prativadas/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/prativadas/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/prativadas/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/prativadas"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104/comments",
    "created_at": "2017-12-30T05:30:49Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/104",
    "id": 285185300,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUyODUxODUzMDA=",
    "number": 104,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104/timeline",
    "title": "  libpoppler.so.71: cannot open shared object file: No such file or directory",
    "updated_at": "2019-03-16T17:15:43Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/104",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/22513019?v=4",
        "events_url": "https://api.github.com/users/xigrug/events{/privacy}",
        "followers_url": "https://api.github.com/users/xigrug/followers",
        "following_url": "https://api.github.com/users/xigrug/following{/other_user}",
        "gists_url": "https://api.github.com/users/xigrug/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/xigrug",
        "id": 22513019,
        "login": "xigrug",
        "node_id": "MDQ6VXNlcjIyNTEzMDE5",
        "organizations_url": "https://api.github.com/users/xigrug/orgs",
        "received_events_url": "https://api.github.com/users/xigrug/received_events",
        "repos_url": "https://api.github.com/users/xigrug/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/xigrug/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/xigrug/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/xigrug"
    }
}