{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "(Sorry for multiple edits) The label string does not allow for two words to be separated by a space.\r\n\r\n**Full code that generated the error**\r\n\r\n```python\r\nfig.plot(x=df_mis.lon, y=df_mis.lat, \r\n         pen=f'0.5p,{c_pen}', style='s0.15', color=c_mis, transparency=50, \r\n         label='Mining events')\r\n```\r\n\r\n**Full error message**\r\n\r\n```\r\nplot [ERROR]: Cannot find file events\r\n---------------------------------------------------------------------------\r\nGMTCLibError                              Traceback (most recent call last)\r\nInput In [279], in <module>\r\n     22 fig.plot(x=df_eq.lon, y=df_eq.lat, \r\n     23          pen=f'0.5p,{c_pen}', style='c0.1', color=c_eq, transparency=50, \r\n     24          label='Earthquake')\r\n     25 fig.plot(x=df_ex.lon, y=df_ex.lat, \r\n     26          pen=f'1p,{c_ex}', style='x0.15', transparency=40, \r\n     27          label='Explosion')\r\n---> 28 fig.plot(x=df_mis.lon, y=df_mis.lat, \r\n     29          pen=f'0.5p,{c_pen}', style='s0.15', color=c_mis, transparency=50, \r\n     30          label='Mining events')\r\n     31 fig.legend()\r\n     33 # right plot\r\n\r\nFile [path to env]/lib/python3.10/site-packages/pygmt/helpers/decorators.py:805, in deprecate_parameter.<locals>.deprecator.<locals>.new_module(*args, **kwargs)\r\n    803     warnings.warn(msg, category=FutureWarning, stacklevel=2)\r\n    804     kwargs[newname] = kwargs.pop(oldname)\r\n--> 805 return module_func(*args, **kwargs)\r\n\r\nFile [path to env]/lib/python3.10/site-packages/pygmt/helpers/decorators.py:805, in deprecate_parameter.<locals>.deprecator.<locals>.new_module(*args, **kwargs)\r\n    803     warnings.warn(msg, category=FutureWarning, stacklevel=2)\r\n    804     kwargs[newname] = kwargs.pop(oldname)\r\n--> 805 return module_func(*args, **kwargs)\r\n\r\nFile [path to env]/lib/python3.10/site-packages/pygmt/helpers/decorators.py:873, in check_data_input_order.<locals>.data_input_order_checker.<locals>.new_module(*args, **kwargs)\r\n    865     msg = (\r\n    866         \"The function parameters has been re-ordered as 'data, x, y, [z]' \"\r\n    867         f\"since {deprecate_version} but you're passing positional arguments. \"\r\n   (...)\r\n    870         f\"in {remove_version}.\"\r\n    871     )\r\n    872     warnings.warn(msg, category=FutureWarning, stacklevel=2)\r\n--> 873 return module_func(*args, **kwargs)\r\n\r\nFile [path to env]/lib/python3.10/site-packages/pygmt/helpers/decorators.py:586, in use_alias.<locals>.alias_decorator.<locals>.new_module(*args, **kwargs)\r\n    581         msg = (\r\n    582             f\"Short-form parameter ({short_param}) is not recommended. \"\r\n    583             f\"Use long-form parameter '{long_alias}' instead.\"\r\n    584         )\r\n    585         warnings.warn(msg, category=SyntaxWarning, stacklevel=2)\r\n--> 586 return module_func(*args, **kwargs)\r\n\r\nFile [path to env]/lib/python3.10/site-packages/pygmt/helpers/decorators.py:726, in kwargs_to_strings.<locals>.converter.<locals>.new_module(*args, **kwargs)\r\n    724             kwargs[arg] = separators[fmt].join(f\"{item}\" for item in value)\r\n    725 # Execute the original function and return its output\r\n--> 726 return module_func(*args, **kwargs)\r\n\r\nFile [path to env]/lib/python3.10/site-packages/pygmt/src/plot.py:275, in plot(self, data, x, y, size, direction, **kwargs)\r\n    273 with file_context as fname:\r\n    274     arg_str = \" \".join([fname, build_arg_string(kwargs)])\r\n--> 275     lib.call_module(\"plot\", arg_str)\r\n\r\nFile [path to env]/lib/python3.10/site-packages/pygmt/clib/session.py:500, in Session.call_module(self, module, args)\r\n    496 status = c_call_module(\r\n    497     self.session_pointer, module.encode(), mode, args.encode()\r\n    498 )\r\n    499 if status != 0:\r\n--> 500     raise GMTCLibError(\r\n    501         f\"Module '{module}' failed with status code {status}:\\n{self._error_message}\"\r\n    502     )\r\n\r\nGMTCLibError: Module 'plot' failed with status code 72:\r\nplot [ERROR]: Cannot find file events\r\n\r\n```\r\n\r\n**System information**\r\n\r\n```\r\nPyGMT information:\r\n  version: v0.5.0\r\nSystem information:\r\n  python: 3.10.2 | packaged by conda-forge | (main, Jan 14 2022, 08:02:19) [GCC 9.4.0]\r\n  executable: [path to env]/bin/python\r\n  machine: Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.17\r\nDependency information:\r\n  numpy: 1.21.5\r\n  pandas: 1.3.5\r\n  xarray: 0.19.0\r\n  netCDF4: 1.5.8\r\n  packaging: 21.3\r\n  ghostscript: 9.54.0\r\n  gmt: 6.3.0\r\nGMT library information:\r\n  binary dir:[path to env]/bin\r\n  cores: 64\r\n  grid layout: rows\r\n  library path: [path to env]/lib/libgmt.so\r\n  padding: 2\r\n  plugin dir: [path to env]/lib/gmt/plugins\r\n  share dir: [path to env]/share/gmt\r\n  version: 6.3.0\r\n```\r\n",
    "closed_at": "2022-03-27T05:14:01Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    },
    "comments": 2,
    "comments_content": [
        {
            "author_association": "NONE",
            "body": "\ud83d\udc4b Thanks for opening your first issue here! Please make sure you filled out the template with as much detail as possible. You might also want to take a look at our [contributing guidelines](https://github.com/GenericMappingTools/pygmt/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/GenericMappingTools/pygmt/blob/main/CODE_OF_CONDUCT.md).\n",
            "created_at": "2022-03-26T19:03:28Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1849#issuecomment-1079755555",
            "id": 1079755555,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1849",
            "node_id": "IC_kwDOBRZfO85AW8Mj",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1079755555/reactions"
            },
            "updated_at": "2022-03-26T19:03:28Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1079755555",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/in/4141?v=4",
                "events_url": "https://api.github.com/users/welcome%5Bbot%5D/events{/privacy}",
                "followers_url": "https://api.github.com/users/welcome%5Bbot%5D/followers",
                "following_url": "https://api.github.com/users/welcome%5Bbot%5D/following{/other_user}",
                "gists_url": "https://api.github.com/users/welcome%5Bbot%5D/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/apps/welcome",
                "id": 30606887,
                "login": "welcome[bot]",
                "node_id": "MDM6Qm90MzA2MDY4ODc=",
                "organizations_url": "https://api.github.com/users/welcome%5Bbot%5D/orgs",
                "received_events_url": "https://api.github.com/users/welcome%5Bbot%5D/received_events",
                "repos_url": "https://api.github.com/users/welcome%5Bbot%5D/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/welcome%5Bbot%5D/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/welcome%5Bbot%5D/subscriptions",
                "type": "Bot",
                "url": "https://api.github.com/users/welcome%5Bbot%5D"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Hi @seismomomo, this space issue has been fixed in #1487 and is available in the latest version of PyGMT (v0.6.0), so you can upgrade to get the fix.\n\nAlternatively if you want to stay on PyGMT v0.5.0, use `label='\"Some label\"'` (double quotes inside single quotes). See #247 or #1632 for a longer explanation.",
            "created_at": "2022-03-26T20:32:57Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1849#issuecomment-1079769944",
            "id": 1079769944,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1849",
            "node_id": "IC_kwDOBRZfO85AW_tY",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1079769944/reactions"
            },
            "updated_at": "2022-03-26T20:36:06Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1079769944",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1849/comments",
    "created_at": "2022-03-26T19:03:26Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1849/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1849",
    "id": 1181990464,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        },
        {
            "color": "cccccc",
            "default": true,
            "description": "This issue or pull request already exists",
            "id": 563309828,
            "name": "duplicate",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjg=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/duplicate"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1849/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOBRZfO85Gc75A",
    "number": 1849,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1849/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1849/timeline",
    "title": "Plot labels do not allow spaces",
    "updated_at": "2022-03-27T10:46:17Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1849",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/52010224?v=4",
        "events_url": "https://api.github.com/users/seismomomo/events{/privacy}",
        "followers_url": "https://api.github.com/users/seismomomo/followers",
        "following_url": "https://api.github.com/users/seismomomo/following{/other_user}",
        "gists_url": "https://api.github.com/users/seismomomo/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seismomomo",
        "id": 52010224,
        "login": "seismomomo",
        "node_id": "MDQ6VXNlcjUyMDEwMjI0",
        "organizations_url": "https://api.github.com/users/seismomomo/orgs",
        "received_events_url": "https://api.github.com/users/seismomomo/received_events",
        "repos_url": "https://api.github.com/users/seismomomo/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seismomomo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seismomomo/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seismomomo"
    }
}