{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "## Description of the problem\r\n\r\nHi I followed the tutorial to install pygmt and gmt through conda [[described here]](https://www.pygmt.org/dev/install.html). But I am running through a lot of faillure when running pygmt.test().\r\n\r\nAny idea why? Should I try a less recent version of python?\r\n\r\n## Full code that generated the error \r\n\r\n```python\r\nIn [1]: import pygmt                                                                                                                                                                                                                                               \r\nIn [2]: pygmt.test()   \r\n```\r\n**53 tests failed, 212 passed, 1 skipped**\r\n## Full error message\r\n\r\n<details>\r\n  <summary>Click to expand!</summary>\r\n\r\n```python\r\nIn [2]: pygmt.test()                                                                                                                                                                                                                                               \r\nPyGMT information:\r\n  version: v0.1.2\r\nSystem information:\r\n  python: 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:21:09)  [Clang 9.0.1 ]\r\n  executable: /Users/locupe/anaconda2/envs/pygmt/bin/python\r\n  machine: macOS-10.15.5-x86_64-i386-64bit\r\nDependency information:\r\n  numpy: 1.18.5\r\n  pandas: 1.0.5\r\n  xarray: 0.15.1\r\n  netCDF4: 1.5.3\r\n  packaging: 20.4\r\n  ghostscript: 9.22\r\n  gmt: 6.1.0\r\nGMT library information:\r\n  binary dir: /Users/locupe/anaconda2/envs/pygmt/bin\r\n  cores: 12\r\n  grid layout: rows\r\n  library path: /Users/locupe/anaconda2/envs/pygmt/lib/libgmt.dylib\r\n  padding: 2\r\n  plugin dir: /Users/locupe/anaconda2/envs/pygmt/lib/gmt/plugins\r\n  share dir: /Users/locupe/anaconda2/envs/pygmt/share/gmt\r\n  version: 6.1.0\r\n======================================================================================================================= test session starts =======================================================================================================================\r\nplatform darwin -- Python 3.8.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /Users/locupe/anaconda2/envs/pygmt/bin/python\r\ncachedir: .pytest_cache\r\nMatplotlib: 3.2.2\r\nFreetype: 2.10.2\r\nrootdir: /Users/locupe/Dropbox/Work/Python/Repos_perso/analysis_eel_data\r\nplugins: mpl-0.11\r\ncollected 266 items                                                                                                                                                                                                                                               \r\n\r\nbase_plotting.py::pygmt.base_plotting.BasePlotting._preprocess <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/base_plotting.py PASSED                                                                                             [  0%]\r\nfigure.py::pygmt.figure.Figure <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/figure.py PASSED                                                                                                                                    [  0%]\r\nclib/conversion.py::pygmt.clib.conversion.as_c_contiguous <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/conversion.py PASSED                                                                                                [  1%]\r\nclib/conversion.py::pygmt.clib.conversion.dataarray_to_matrix <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/conversion.py FAILED                                                                                            [  1%]\r\nclib/conversion.py::pygmt.clib.conversion.kwargs_to_ctypes_array <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/conversion.py PASSED                                                                                         [  1%]\r\nclib/conversion.py::pygmt.clib.conversion.vectors_to_arrays <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/conversion.py PASSED                                                                                              [  2%]\r\nclib/session.py::pygmt.clib.session.Session <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/session.py FAILED                                                                                                                 [  2%]\r\nclib/session.py::pygmt.clib.session.Session._check_dtype_and_dim <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/session.py PASSED                                                                                            [  3%]\r\nclib/session.py::pygmt.clib.session.Session.extract_region <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/session.py PASSED                                                                                                  [  3%]\r\nclib/session.py::pygmt.clib.session.Session.get_libgmt_func <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/session.py PASSED                                                                                                 [  3%]\r\nclib/session.py::pygmt.clib.session.Session.open_virtual_file <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/session.py PASSED                                                                                               [  4%]\r\nclib/session.py::pygmt.clib.session.Session.virtualfile_from_grid <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/session.py FAILED                                                                                           [  4%]\r\nclib/session.py::pygmt.clib.session.Session.virtualfile_from_matrix <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/session.py PASSED                                                                                         [  4%]\r\nclib/session.py::pygmt.clib.session.Session.virtualfile_from_vectors <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/session.py PASSED                                                                                        [  5%]\r\ndatasets/earth_relief.py::pygmt.datasets.earth_relief._is_valid_resolution <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/datasets/earth_relief.py PASSED                                                                         [  5%]\r\ndatasets/earth_relief.py::pygmt.datasets.earth_relief._shape_from_resolution <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/datasets/earth_relief.py PASSED                                                                       [  6%]\r\nhelpers/decorators.py::pygmt.helpers.decorators.fmt_docstring <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/helpers/decorators.py PASSED                                                                                         [  6%]\r\nhelpers/decorators.py::pygmt.helpers.decorators.kwargs_to_strings <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/helpers/decorators.py PASSED                                                                                     [  6%]\r\nhelpers/decorators.py::pygmt.helpers.decorators.use_alias <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/helpers/decorators.py PASSED                                                                                             [  7%]\r\nhelpers/tempfile.py::pygmt.helpers.tempfile.GMTTempFile <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/helpers/tempfile.py PASSED                                                                                                 [  7%]\r\nhelpers/utils.py::pygmt.helpers.utils.build_arg_string <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/helpers/utils.py PASSED                                                                                                     [  7%]\r\nhelpers/utils.py::pygmt.helpers.utils.data_kind <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/helpers/utils.py PASSED                                                                                                            [  8%]\r\nhelpers/utils.py::pygmt.helpers.utils.dummy_context <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/helpers/utils.py PASSED                                                                                                        [  8%]\r\nhelpers/utils.py::pygmt.helpers.utils.is_nonstr_iter <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/helpers/utils.py PASSED                                                                                                       [  9%]\r\ntests/test_basemap.py::test_basemap_required_args <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_basemap.py PASSED                                                                                                     [  9%]\r\ntests/test_basemap.py::test_basemap <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_basemap.py PASSED                                                                                                                   [  9%]\r\ntests/test_basemap.py::test_basemap_list_region <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_basemap.py PASSED                                                                                                       [ 10%]\r\ntests/test_basemap.py::test_basemap_loglog <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_basemap.py PASSED                                                                                                            [ 10%]\r\ntests/test_basemap.py::test_basemap_power_axis <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_basemap.py PASSED                                                                                                        [ 10%]\r\ntests/test_basemap.py::test_basemap_polar <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_basemap.py FAILED                                                                                                             [ 11%]\r\ntests/test_basemap.py::test_basemap_winkel_tripel <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_basemap.py PASSED                                                                                                     [ 11%]\r\ntests/test_basemap.py::test_basemap_aliases <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_basemap.py PASSED                                                                                                           [ 12%]\r\ntests/test_blockmedian.py::test_blockmedian_input_dataframe <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_blockmedian.py PASSED                                                                                       [ 12%]\r\ntests/test_blockmedian.py::test_blockmedian_wrong_kind_of_input_table_matrix <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_blockmedian.py PASSED                                                                      [ 12%]\r\ntests/test_blockmedian.py::test_blockmedian_wrong_kind_of_input_table_grid <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_blockmedian.py PASSED                                                                        [ 13%]\r\ntests/test_blockmedian.py::test_blockmedian_input_filename <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_blockmedian.py PASSED                                                                                        [ 13%]\r\ntests/test_blockmedian.py::test_blockmedian_without_outfile_setting <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_blockmedian.py PASSED                                                                               [ 13%]\r\ntests/test_clib.py::test_getitem <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                                         [ 14%]\r\ntests/test_clib.py::test_create_destroy_session <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                          [ 14%]\r\ntests/test_clib.py::test_create_session_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                            [ 15%]\r\ntests/test_clib.py::test_destroy_session_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                           [ 15%]\r\ntests/test_clib.py::test_call_module <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                                     [ 15%]\r\ntests/test_clib.py::test_call_module_invalid_arguments <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                   [ 16%]\r\ntests/test_clib.py::test_call_module_invalid_name <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                        [ 16%]\r\ntests/test_clib.py::test_call_module_error_message <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py FAILED                                                                                                       [ 16%]\r\ntests/test_clib.py::test_method_no_session <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                               [ 17%]\r\ntests/test_clib.py::test_parse_constant_single <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                           [ 17%]\r\ntests/test_clib.py::test_parse_constant_composite <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                        [ 18%]\r\ntests/test_clib.py::test_parse_constant_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                            [ 18%]\r\ntests/test_clib.py::test_create_data_dataset <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                             [ 18%]\r\ntests/test_clib.py::test_create_data_grid_dim <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                            [ 19%]\r\ntests/test_clib.py::test_create_data_grid_range <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                          [ 19%]\r\ntests/test_clib.py::test_create_data_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                               [ 19%]\r\ntests/test_clib.py::test_put_vector <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                                      [ 20%]\r\ntests/test_clib.py::test_put_vector_invalid_dtype <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                        [ 20%]\r\ntests/test_clib.py::test_put_vector_wrong_column <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                         [ 21%]\r\ntests/test_clib.py::test_put_vector_2d_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                             [ 21%]\r\ntests/test_clib.py::test_put_matrix <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                                      [ 21%]\r\ntests/test_clib.py::test_put_matrix_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                                [ 22%]\r\ntests/test_clib.py::test_put_matrix_grid <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                                 [ 22%]\r\ntests/test_clib.py::test_virtual_file <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                                    [ 22%]\r\ntests/test_clib.py::test_virtual_file_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                              [ 23%]\r\ntests/test_clib.py::test_virtual_file_bad_direction <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                      [ 23%]\r\ntests/test_clib.py::test_virtualfile_from_vectors <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                        [ 24%]\r\ntests/test_clib.py::test_virtualfile_from_vectors_transpose <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                              [ 24%]\r\ntests/test_clib.py::test_virtualfile_from_vectors_diff_size <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                              [ 24%]\r\ntests/test_clib.py::test_virtualfile_from_matrix <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                         [ 25%]\r\ntests/test_clib.py::test_virtualfile_from_matrix_slice <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                   [ 25%]\r\ntests/test_clib.py::test_virtualfile_from_vectors_pandas <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                 [ 25%]\r\ntests/test_clib.py::test_virtualfile_from_vectors_arraylike <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                              [ 26%]\r\ntests/test_clib.py::test_extract_region_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                            [ 26%]\r\ntests/test_clib.py::test_extract_region_two_figures <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                      [ 27%]\r\ntests/test_clib.py::test_write_data_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                                [ 27%]\r\ntests/test_clib.py::test_dataarray_to_matrix_works <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                       [ 27%]\r\ntests/test_clib.py::test_dataarray_to_matrix_negative_x_increment <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                        [ 28%]\r\ntests/test_clib.py::test_dataarray_to_matrix_negative_y_increment <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                        [ 28%]\r\ntests/test_clib.py::test_dataarray_to_matrix_negative_x_and_y_increment <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                  [ 28%]\r\ntests/test_clib.py::test_dataarray_to_matrix_dims_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                  [ 29%]\r\ntests/test_clib.py::test_dataarray_to_matrix_inc_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                   [ 29%]\r\ntests/test_clib.py::test_get_default <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                                     [ 30%]\r\ntests/test_clib.py::test_get_default_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                               [ 30%]\r\ntests/test_clib.py::test_info_dict <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                                       [ 30%]\r\ntests/test_clib.py::test_fails_for_wrong_version <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py PASSED                                                                                                         [ 31%]\r\ntests/test_clib_loading.py::test_check_libgmt <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib_loading.py PASSED                                                                                                    [ 31%]\r\ntests/test_clib_loading.py::test_load_libgmt <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib_loading.py PASSED                                                                                                     [ 31%]\r\ntests/test_clib_loading.py::test_load_libgmt_fail <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib_loading.py PASSED                                                                                                [ 32%]\r\ntests/test_clib_loading.py::test_clib_names <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib_loading.py PASSED                                                                                                      [ 32%]\r\ntests/test_coast.py::test_coast <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_coast.py PASSED                                                                                                                         [ 33%]\r\ntests/test_coast.py::test_coast_iceland <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_coast.py FAILED                                                                                                                 [ 33%]\r\ntests/test_coast.py::test_coast_aliases <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_coast.py PASSED                                                                                                                 [ 33%]\r\ntests/test_coast.py::test_coast_world_mercator <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_coast.py PASSED                                                                                                          [ 34%]\r\ntests/test_colorbar.py::test_colorbar_using_paper_coordinates <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py PASSED                                                                                        [ 34%]\r\ntests/test_colorbar.py::test_colorbar_using_paper_coordinates_horizontal <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py PASSED                                                                             [ 34%]\r\ntests/test_colorbar.py::test_colorbar_positioned_using_map_coordinates <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py PASSED                                                                               [ 35%]\r\ntests/test_colorbar.py::test_colorbar_positioned_using_justification_code <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py FAILED                                                                            [ 35%]\r\ntests/test_colorbar.py::test_colorbar_positioned_using_normalized_coords <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py PASSED                                                                             [ 36%]\r\ntests/test_colorbar.py::test_colorbar_box <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py PASSED                                                                                                            [ 36%]\r\ntests/test_colorbar.py::test_colorbar_box_with_pen <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py PASSED                                                                                                   [ 36%]\r\ntests/test_colorbar.py::test_colorbar_box_with_fill <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py PASSED                                                                                                  [ 37%]\r\ntests/test_colorbar.py::test_colorbar_box_with_clearance <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py PASSED                                                                                             [ 37%]\r\ntests/test_colorbar.py::test_colorbar_box_with_secondary_border <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py PASSED                                                                                      [ 37%]\r\ntests/test_colorbar.py::test_colorbar_box_with_rounded_corners <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py PASSED                                                                                       [ 38%]\r\ntests/test_colorbar.py::test_colorbar_box_with_offset_background <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py PASSED                                                                                     [ 38%]\r\ntests/test_colorbar.py::test_colorbar_truncated_to_zlow_zhigh <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py PASSED                                                                                        [ 39%]\r\ntests/test_colorbar.py::test_colorbar_scaled_z_values <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_colorbar.py PASSED                                                                                                [ 39%]\r\ntests/test_config.py::test_config <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_config.py FAILED                                                                                                                      [ 39%]\r\ntests/test_config.py::test_config_font_one <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_config.py FAILED                                                                                                             [ 40%]\r\ntests/test_config.py::test_config_font_annot <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_config.py FAILED                                                                                                           [ 40%]\r\ntests/test_config.py::test_config_format_time_map <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_config.py PASSED                                                                                                      [ 40%]\r\ntests/test_config.py::test_config_map_annot_offset <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_config.py PASSED                                                                                                     [ 41%]\r\ntests/test_config.py::test_config_map_grid_cross_size <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_config.py PASSED                                                                                                  [ 41%]\r\ntests/test_config.py::test_config_map_grid_pen <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_config.py PASSED                                                                                                         [ 42%]\r\ntests/test_config.py::test_config_map_tick_length <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_config.py PASSED                                                                                                      [ 42%]\r\ntests/test_config.py::test_config_map_tick_pen <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_config.py PASSED                                                                                                         [ 42%]\r\ntests/test_contour.py::test_contour_fail_no_data <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_contour.py PASSED                                                                                                      [ 43%]\r\ntests/test_contour.py::test_contour_vec <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_contour.py PASSED                                                                                                               [ 43%]\r\ntests/test_contour.py::test_contour_matrix <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_contour.py PASSED                                                                                                            [ 43%]\r\ntests/test_contour.py::test_contour_from_file <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_contour.py PASSED                                                                                                         [ 44%]\r\ntests/test_datasets.py::test_japan_quakes <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_datasets.py PASSED                                                                                                            [ 44%]\r\ntests/test_datasets.py::test_ocean_ridge_points <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_datasets.py PASSED                                                                                                      [ 45%]\r\ntests/test_datasets.py::test_sample_bathymetry <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_datasets.py PASSED                                                                                                       [ 45%]\r\ntests/test_datasets.py::test_usgs_quakes <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_datasets.py PASSED                                                                                                             [ 45%]\r\ntests/test_datasets.py::test_earth_relief_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_datasets.py PASSED                                                                                                      [ 46%]\r\ntests/test_datasets.py::test_earth_relief_01d <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_datasets.py FAILED                                                                                                        [ 46%]\r\ntests/test_datasets.py::test_earth_relief_30m <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_datasets.py FAILED                                                                                                        [ 46%]\r\ntests/test_figure.py::test_figure_region <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_figure.py PASSED                                                                                                               [ 47%]\r\ntests/test_figure.py::test_figure_region_multiple <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_figure.py PASSED                                                                                                      [ 47%]\r\ntests/test_figure.py::test_figure_region_country_codes <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_figure.py PASSED                                                                                                 [ 48%]\r\ntests/test_figure.py::test_figure_savefig_exists <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_figure.py PASSED                                                                                                       [ 48%]\r\ntests/test_figure.py::test_figure_savefig_transparent <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_figure.py PASSED                                                                                                  [ 48%]\r\ntests/test_figure.py::test_figure_savefig <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_figure.py PASSED                                                                                                              [ 49%]\r\ntests/test_figure.py::test_figure_show <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_figure.py PASSED                                                                                                                 [ 49%]\r\ntests/test_figure.py::test_shift_origin <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_figure.py PASSED                                                                                                                [ 50%]\r\ntests/test_grdcontour.py::test_grdcontour <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcontour.py FAILED                                                                                                          [ 50%]\r\ntests/test_grdcontour.py::test_grdcontour_labels <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcontour.py FAILED                                                                                                   [ 50%]\r\ntests/test_grdcontour.py::test_grdcontour_slice <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcontour.py FAILED                                                                                                    [ 51%]\r\ntests/test_grdcontour.py::test_grdcontour_file <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcontour.py FAILED                                                                                                     [ 51%]\r\ntests/test_grdcontour.py::test_grdcontour_interval_file_full_opts <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcontour.py FAILED                                                                                  [ 51%]\r\ntests/test_grdcontour.py::test_grdcontour_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcontour.py PASSED                                                                                                    [ 52%]\r\ntests/test_grdcut.py::test_grdcut_file_in_file_out <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcut.py FAILED                                                                                                     [ 52%]\r\ntests/test_grdcut.py::test_grdcut_file_in_dataarray_out <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcut.py FAILED                                                                                                [ 53%]\r\ntests/test_grdcut.py::test_grdcut_dataarray_in_file_out <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcut.py PASSED                                                                                                [ 53%]\r\ntests/test_grdcut.py::test_grdcut_dataarray_in_dataarray_out <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcut.py PASSED                                                                                           [ 53%]\r\ntests/test_grdcut.py::test_grdcut_dataarray_in_fail <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcut.py PASSED                                                                                                    [ 54%]\r\ntests/test_grdcut.py::test_grdcut_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcut.py PASSED                                                                                                                [ 54%]\r\ntests/test_grdimage.py::test_grdimage <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdimage.py FAILED                                                                                                                [ 54%]\r\ntests/test_grdimage.py::test_grdimage_slice <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdimage.py FAILED                                                                                                          [ 55%]\r\ntests/test_grdimage.py::test_grdimage_file <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdimage.py FAILED                                                                                                           [ 55%]\r\ntests/test_grdimage.py::test_grdimage_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdimage.py PASSED                                                                                                          [ 56%]\r\ntests/test_grdinfo.py::test_grdinfo <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdinfo.py FAILED                                                                                                                   [ 56%]\r\ntests/test_grdinfo.py::test_grdinfo_file <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdinfo.py FAILED                                                                                                              [ 56%]\r\ntests/test_grdinfo.py::test_grdinfo_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdinfo.py PASSED                                                                                                             [ 57%]\r\ntests/test_grdtrack.py::test_grdtrack_input_dataframe_and_dataarray <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdtrack.py FAILED                                                                                  [ 57%]\r\ntests/test_grdtrack.py::test_grdtrack_input_csvfile_and_dataarray <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdtrack.py FAILED                                                                                    [ 57%]\r\ntests/test_grdtrack.py::test_grdtrack_input_dataframe_and_ncfile <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdtrack.py FAILED                                                                                     [ 58%]\r\ntests/test_grdtrack.py::test_grdtrack_input_csvfile_and_ncfile <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdtrack.py FAILED                                                                                       [ 58%]\r\ntests/test_grdtrack.py::test_grdtrack_wrong_kind_of_points_input <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdtrack.py PASSED                                                                                     [ 59%]\r\ntests/test_grdtrack.py::test_grdtrack_wrong_kind_of_grid_input <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdtrack.py PASSED                                                                                       [ 59%]\r\ntests/test_grdtrack.py::test_grdtrack_without_newcolname_setting <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdtrack.py PASSED                                                                                     [ 59%]\r\ntests/test_grdtrack.py::test_grdtrack_without_outfile_setting <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdtrack.py PASSED                                                                                        [ 60%]\r\ntests/test_grdview.py::test_grdview_grid_dataarray <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                                                    [ 60%]\r\ntests/test_grdview.py::test_grdview_grid_file_with_region_subset <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                                      [ 60%]\r\ntests/test_grdview.py::test_grdview_wrong_kind_of_grid <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py PASSED                                                                                                [ 61%]\r\ntests/test_grdview.py::test_grdview_with_perspective <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                                                  [ 61%]\r\ntests/test_grdview.py::test_grdview_with_perspective_and_zscale <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                                       [ 62%]\r\ntests/test_grdview.py::test_grdview_with_perspective_and_zsize <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                                        [ 62%]\r\ntests/test_grdview.py::test_grdview_with_cmap_for_image_plot <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                                          [ 62%]\r\ntests/test_grdview.py::test_grdview_with_cmap_for_surface_monochrome_plot <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                             [ 63%]\r\ntests/test_grdview.py::test_grdview_with_cmap_for_perspective_surface_plot <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                            [ 63%]\r\ntests/test_grdview.py::test_grdview_on_a_plane <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                                                        [ 63%]\r\ntests/test_grdview.py::test_grdview_on_a_plane_with_colored_frontal_facade <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                            [ 64%]\r\ntests/test_grdview.py::test_grdview_with_perspective_and_zaxis_frame <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                                  [ 64%]\r\ntests/test_grdview.py::test_grdview_surface_plot_styled_with_contourpen <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                               [ 65%]\r\ntests/test_grdview.py::test_grdview_surface_mesh_plot_styled_with_meshpen <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                             [ 65%]\r\ntests/test_grdview.py::test_grdview_on_a_plane_styled_with_facadepen <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                                  [ 65%]\r\ntests/test_grdview.py::test_grdview_drapegrid_dataarray <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py FAILED                                                                                               [ 66%]\r\ntests/test_grdview.py::test_grdview_wrong_kind_of_drapegrid <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdview.py PASSED                                                                                           [ 66%]\r\ntests/test_helpers.py::test_data_kind_fails[None-None-None] <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_helpers.py PASSED                                                                                           [ 66%]\r\ntests/test_helpers.py::test_data_kind_fails[data.txt-x1-y1] <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_helpers.py PASSED                                                                                           [ 67%]\r\ntests/test_helpers.py::test_data_kind_fails[data.txt-x2-None] <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_helpers.py PASSED                                                                                         [ 67%]\r\ntests/test_helpers.py::test_data_kind_fails[data.txt-None-y3] <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_helpers.py PASSED                                                                                         [ 68%]\r\ntests/test_helpers.py::test_data_kind_fails[None-x4-None] <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_helpers.py PASSED                                                                                             [ 68%]\r\ntests/test_helpers.py::test_data_kind_fails[None-None-y5] <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_helpers.py PASSED                                                                                             [ 68%]\r\ntests/test_helpers.py::test_unique_name <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_helpers.py PASSED                                                                                                               [ 69%]\r\ntests/test_helpers.py::test_kwargs_to_strings_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_helpers.py PASSED                                                                                                   [ 69%]\r\ntests/test_helpers.py::test_kwargs_to_strings_no_bools <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_helpers.py PASSED                                                                                                [ 69%]\r\ntests/test_helpers.py::test_gmttempfile <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_helpers.py PASSED                                                                                                               [ 70%]\r\ntests/test_helpers.py::test_gmttempfile_unique <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_helpers.py PASSED                                                                                                        [ 70%]\r\ntests/test_helpers.py::test_gmttempfile_prefix_suffix <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_helpers.py PASSED                                                                                                 [ 71%]\r\ntests/test_helpers.py::test_gmttempfile_read <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_helpers.py PASSED                                                                                                          [ 71%]\r\ntests/test_image.py::test_image <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_image.py PASSED                                                                                                                         [ 71%]\r\ntests/test_info.py::test_info <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_info.py PASSED                                                                                                                            [ 72%]\r\ntests/test_info.py::test_info_per_column <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_info.py PASSED                                                                                                                 [ 72%]\r\ntests/test_info.py::test_info_spacing <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_info.py PASSED                                                                                                                    [ 72%]\r\ntests/test_info.py::test_info_per_column_spacing <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_info.py PASSED                                                                                                         [ 73%]\r\ntests/test_info.py::test_info_nearest_multiple <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_info.py PASSED                                                                                                           [ 73%]\r\ntests/test_info.py::test_info_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_info.py PASSED                                                                                                                      [ 74%]\r\ntests/test_legend.py::test_legend_position <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_legend.py PASSED                                                                                                             [ 74%]\r\ntests/test_legend.py::test_legend_default_position <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_legend.py PASSED                                                                                                     [ 74%]\r\ntests/test_legend.py::test_legend_entries <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_legend.py FAILED                                                                                                              [ 75%]\r\ntests/test_legend.py::test_legend_specfile <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_legend.py PASSED                                                                                                             [ 75%]\r\ntests/test_legend.py::test_legend_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_legend.py PASSED                                                                                                                [ 75%]\r\ntests/test_logo.py::test_logo <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_logo.py PASSED                                                                                                                            [ 76%]\r\ntests/test_logo.py::test_logo_on_a_map <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_logo.py PASSED                                                                                                                   [ 76%]\r\ntests/test_logo.py::test_logo_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_logo.py PASSED                                                                                                                      [ 77%]\r\ntests/test_makecpt.py::test_makecpt_to_plot_points <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_makecpt.py PASSED                                                                                                    [ 77%]\r\ntests/test_makecpt.py::test_makecpt_to_plot_grid <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_makecpt.py FAILED                                                                                                      [ 77%]\r\ntests/test_makecpt.py::test_makecpt_to_plot_grid_scaled_with_series <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_makecpt.py FAILED                                                                                   [ 78%]\r\ntests/test_makecpt.py::test_makecpt_output_to_cpt_file <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_makecpt.py PASSED                                                                                                [ 78%]\r\ntests/test_makecpt.py::test_makecpt_blank_output <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_makecpt.py PASSED                                                                                                      [ 78%]\r\ntests/test_makecpt.py::test_makecpt_invalid_output <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_makecpt.py PASSED                                                                                                    [ 79%]\r\ntests/test_makecpt.py::test_makecpt_truncated_to_zlow_zhigh <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_makecpt.py FAILED                                                                                           [ 79%]\r\ntests/test_makecpt.py::test_makecpt_truncated_at_zlow_only <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_makecpt.py FAILED                                                                                            [ 80%]\r\ntests/test_makecpt.py::test_makecpt_truncated_at_zhigh_only <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_makecpt.py FAILED                                                                                           [ 80%]\r\ntests/test_makecpt.py::test_makecpt_reverse_color_only <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_makecpt.py FAILED                                                                                                [ 80%]\r\ntests/test_makecpt.py::test_makecpt_reverse_zsign_only <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_makecpt.py FAILED                                                                                                [ 81%]\r\ntests/test_makecpt.py::test_makecpt_reverse_color_and_zsign <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_makecpt.py FAILED                                                                                           [ 81%]\r\ntests/test_makecpt.py::test_makecpt_continuous <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_makecpt.py FAILED                                                                                                        [ 81%]\r\ntests/test_plot.py::test_plot_red_circles <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                                [ 82%]\r\ntests/test_plot.py::test_plot_fail_no_data <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                               [ 82%]\r\ntests/test_plot.py::test_plot_fail_size_color <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                            [ 83%]\r\ntests/test_plot.py::test_plot_projection <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                                 [ 83%]\r\ntests/test_plot.py::test_plot_colors <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                                     [ 83%]\r\ntests/test_plot.py::test_plot_sizes <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                                      [ 84%]\r\ntests/test_plot.py::test_plot_colors_sizes <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                               [ 84%]\r\ntests/test_plot.py::test_plot_colors_sizes_proj <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                          [ 84%]\r\ntests/test_plot.py::test_plot_matrix <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                                     [ 85%]\r\ntests/test_plot.py::test_plot_matrix_color <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                               [ 85%]\r\ntests/test_plot.py::test_plot_from_file <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                                  [ 86%]\r\ntests/test_plot.py::test_plot_vectors <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                                    [ 86%]\r\ntests/test_plot.py::test_plot_lines_with_arrows <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                          [ 86%]\r\ntests/test_plot.py::test_plot_scalar_xy <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_plot.py PASSED                                                                                                                  [ 87%]\r\ntests/test_psconvert.py::test_psconvert <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_psconvert.py PASSED                                                                                                             [ 87%]\r\ntests/test_psconvert.py::test_psconvert_twice <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_psconvert.py PASSED                                                                                                       [ 87%]\r\ntests/test_psconvert.py::test_psconvert_int_options <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_psconvert.py PASSED                                                                                                 [ 88%]\r\ntests/test_psconvert.py::test_psconvert_aliases <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_psconvert.py PASSED                                                                                                     [ 88%]\r\ntests/test_session_management.py::test_begin_end <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_session_management.py PASSED                                                                                           [ 89%]\r\ntests/test_session_management.py::test_gmt_compat_6_is_applied <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_session_management.py PASSED                                                                             [ 89%]\r\ntests/test_sphinx_gallery.py::test_pygmtscraper <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_sphinx_gallery.py SKIPPED                                                                                               [ 89%]\r\ntests/test_surface.py::test_surface_input_file <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_surface.py PASSED                                                                                                        [ 90%]\r\ntests/test_surface.py::test_surface_input_data_array <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_surface.py PASSED                                                                                                  [ 90%]\r\ntests/test_surface.py::test_surface_input_xyz <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_surface.py PASSED                                                                                                         [ 90%]\r\ntests/test_surface.py::test_surface_input_xy_no_z <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_surface.py PASSED                                                                                                     [ 91%]\r\ntests/test_surface.py::test_surface_wrong_kind_of_input <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_surface.py PASSED                                                                                               [ 91%]\r\ntests/test_surface.py::test_surface_with_outfile_param <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_surface.py PASSED                                                                                                [ 92%]\r\ntests/test_surface.py::test_surface_short_aliases <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_surface.py PASSED                                                                                                     [ 92%]\r\ntests/test_text.py::test_text_single_line_of_text <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                        [ 92%]\r\ntests/test_text.py::test_text_multiple_lines_of_text <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                     [ 93%]\r\ntests/test_text.py::test_text_without_text_input <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                         [ 93%]\r\ntests/test_text.py::test_text_input_single_filename <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                      [ 93%]\r\ntests/test_text.py::test_text_input_remote_filename <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                      [ 94%]\r\ntests/test_text.py::test_text_input_multiple_filenames <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                   [ 94%]\r\ntests/test_text.py::test_text_nonexistent_filename <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                       [ 95%]\r\ntests/test_text.py::test_text_position <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                                   [ 95%]\r\ntests/test_text.py::test_text_xy_with_position_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                     [ 95%]\r\ntests/test_text.py::test_text_position_offset_with_line <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                  [ 96%]\r\ntests/test_text.py::test_text_angle_30 <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                                   [ 96%]\r\ntests/test_text.py::test_text_font_bold <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                                  [ 96%]\r\ntests/test_text.py::test_text_fill <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                                       [ 97%]\r\ntests/test_text.py::test_text_pen <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                                        [ 97%]\r\ntests/test_text.py::test_text_round_clearance <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                                            [ 98%]\r\ntests/test_text.py::test_text_justify_bottom_right_and_top_left <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                          [ 98%]\r\ntests/test_text.py::test_text_justify_parsed_from_textfile <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                               [ 98%]\r\ntests/test_text.py::test_text_angle_font_justify_from_textfile <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_text.py PASSED                                                                                           [ 99%]\r\ntests/test_which.py::test_which <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_which.py PASSED                                                                                                                         [ 99%]\r\ntests/test_which.py::test_which_fails <- ../../../../../anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_which.py PASSED                                                                                                                   [100%]\r\n\r\n============================================================================================================================ FAILURES =============================================================================================================================\r\n_______________________________________________________________________________________________________ [doctest] pygmt.clib.conversion.dataarray_to_matrix _______________________________________________________________________________________________________\r\n042         If the grid has more than two dimensions or variable grid spacing.\r\n043 \r\n044     Examples\r\n045     --------\r\n046 \r\n047     >>> from pygmt.datasets import load_earth_relief\r\n048     >>> # Use the global Earth relief grid with 1 degree spacing\r\n049     >>> grid = load_earth_relief(resolution='01d')\r\n050     >>> matrix, region, inc = dataarray_to_matrix(grid)\r\n051     >>> print(region)\r\nExpected:\r\n    [-180.0, 180.0, -90.0, 90.0]\r\nGot:\r\n    [-179.5, 179.5, -89.5, 89.5]\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/conversion.py:51: DocTestFailure\r\n______________________________________________________________________________________________________________ [doctest] pygmt.clib.session.Session _______________________________________________________________________________________________________________\r\n093     --------\r\n094 \r\n095     >>> from pygmt.datasets import load_earth_relief\r\n096     >>> from pygmt.helpers import GMTTempFile\r\n097     >>> grid = load_earth_relief()\r\n098     >>> type(grid)\r\n099     <class 'xarray.core.dataarray.DataArray'>\r\n100     >>> # Create a session and destroy it automatically when exiting the \"with\"\r\n101     >>> # block.\r\n102     >>> with Session() as ses:\r\nExpected:\r\n    -180 180 -90 90 -8592.5 5559 1 1 361 181\r\nGot:\r\n    -179.5 179.5 -89.5 89.5 -8182 5651.5 1 1 360 180 0 0\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/session.py:102: DocTestFailure\r\n___________________________________________________________________________________________________ [doctest] pygmt.clib.session.Session.virtualfile_from_grid ____________________________________________________________________________________________________\r\n271             The name of virtual file. Pass this as a file name argument to a\r\n272             GMT module.\r\n273 \r\n274         Examples\r\n275         --------\r\n276 \r\n277         >>> from pygmt.datasets import load_earth_relief\r\n278         >>> from pygmt.helpers import GMTTempFile\r\n279         >>> data = load_earth_relief(resolution='01d')\r\n280         >>> print(data.shape)\r\nExpected:\r\n    (181, 361)\r\nGot:\r\n    (180, 360)\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/session.py:280: DocTestFailure\r\n_______________________________________________________________________________________________________________________ test_basemap_polar ________________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1958, 1822)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpadq1tydr/baseline-test_basemap_polar.png\r\n  Actual shape: (1957, 1822)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpadq1tydr/test_basemap_polar.png\r\n_________________________________________________________________________________________________________________ test_call_module_error_message __________________________________________________________________________________________________________________\r\n\r\n    def test_call_module_error_message():\r\n        \"Check is the GMT error message was captured.\"\r\n        with clib.Session() as lib:\r\n            try:\r\n>               lib.call_module(\"info\", \"bogus-data.bla\")\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py:159: \r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\r\n\r\nself = <pygmt.clib.session.Session object at 0x7f7f1025f3a0>, module = 'info', args = 'bogus-data.bla'\r\n\r\n    def call_module(self, module, args):\r\n        \"\"\"\r\n        Call a GMT module with the given arguments.\r\n    \r\n        Makes a call to ``GMT_Call_Module`` from the C API using mode\r\n        ``GMT_MODULE_CMD`` (arguments passed as a single string).\r\n    \r\n        Most interactions with the C API are done through this function.\r\n    \r\n        Parameters\r\n        ----------\r\n        module : str\r\n            Module name (``'coast'``, ``'basemap'``, etc).\r\n        args : str\r\n            String with the command line arguments that will be passed to the\r\n            module (for example, ``'-R0/5/0/10 -JM'``).\r\n    \r\n        Raises\r\n        ------\r\n        GMTCLibError\r\n            If the returned status code of the function is non-zero.\r\n    \r\n        \"\"\"\r\n        c_call_module = self.get_libgmt_func(\r\n            \"GMT_Call_Module\",\r\n            argtypes=[ctp.c_void_p, ctp.c_char_p, ctp.c_int, ctp.c_void_p],\r\n            restype=ctp.c_int,\r\n        )\r\n    \r\n        mode = self[\"GMT_MODULE_CMD\"]\r\n        status = c_call_module(\r\n            self.session_pointer, module.encode(), mode, args.encode()\r\n        )\r\n        if status != 0:\r\n>           raise GMTCLibError(\r\n                \"Module '{}' failed with status code {}:\\n{}\".format(\r\n                    module, status, self._error_message\r\n                )\r\n            )\r\nE           pygmt.exceptions.GMTCLibError: Module 'info' failed with status code 71:\r\nE           gmtinfo [ERROR]: Cannot find file bogus-data.bla\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/clib/session.py:498: GMTCLibError\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\n    def test_call_module_error_message():\r\n        \"Check is the GMT error message was captured.\"\r\n        with clib.Session() as lib:\r\n            try:\r\n                lib.call_module(\"info\", \"bogus-data.bla\")\r\n            except GMTCLibError as error:\r\n                msg = \"\\n\".join(\r\n                    [\r\n                        \"Module 'info' failed with status code 71:\",\r\n                        \"gmtinfo [ERROR]: Error for input file: No such file (bogus-data.bla)\",\r\n                    ]\r\n                )\r\n>               assert str(error) == msg\r\nE               assert (\"Module 'info' failed with status code 71:\\n\"\\n 'gmtinfo [ERROR]: Cannot find file bogus-data.bla') == (\"Module 'info' failed with status code 71:\\n\"\\n 'gmtinfo [ERROR]: Error for input file: No such file (bogus-data.bla)')\r\nE                   Module 'info' failed with status code 71:\r\nE                 - gmtinfo [ERROR]: Error for input file: No such file (bogus-data.bla)\r\nE                 + gmtinfo [ERROR]: Cannot find file bogus-data.bla\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_clib.py:167: AssertionError\r\n---------------------------------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------------------------------\r\ngmtinfo [ERROR]: Cannot find file bogus-data.bla\r\n_______________________________________________________________________________________________________________________ test_coast_iceland ________________________________________________________________________________________________________________________\r\nError: Image files did not match.\r\n  RMS Value: 2.1592998456264336\r\n  Expected:  \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpxcaci3oz/baseline-test_coast_iceland.png\r\n  Actual:    \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpxcaci3oz/test_coast_iceland.png\r\n  Difference:\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpxcaci3oz/test_coast_iceland-failed-diff.png\r\n  Tolerance: \r\n    2\r\n________________________________________________________________________________________________________ test_colorbar_positioned_using_justification_code ________________________________________________________________________________________________________\r\nError: Image files did not match.\r\n  RMS Value: 15.679802537698418\r\n  Expected:  \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpy4ttafin/baseline-test_colorbar_positioned_using_justification_code.png\r\n  Actual:    \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpy4ttafin/test_colorbar_positioned_using_justification_code.png\r\n  Difference:\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpy4ttafin/test_colorbar_positioned_using_justification_code-failed-diff.png\r\n  Tolerance: \r\n    2\r\n___________________________________________________________________________________________________________________________ test_config ___________________________________________________________________________________________________________________________\r\nError: Image files did not match.\r\n  RMS Value: 7.013266407484722\r\n  Expected:  \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmplh3taghh/baseline-test_config.png\r\n  Actual:    \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmplh3taghh/test_config.png\r\n  Difference:\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmplh3taghh/test_config-failed-diff.png\r\n  Tolerance: \r\n    2\r\n______________________________________________________________________________________________________________________ test_config_font_one _______________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1526, 1540)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpd_syom1_/baseline-test_config_font_one.png\r\n  Actual shape: (1531, 1545)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpd_syom1_/test_config_font_one.png\r\n_____________________________________________________________________________________________________________________ test_config_font_annot ______________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1161, 1168)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpwi_h0o1v/baseline-test_config_font_annot.png\r\n  Actual shape: (1165, 1172)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpwi_h0o1v/test_config_font_annot.png\r\n______________________________________________________________________________________________________________________ test_earth_relief_01d ______________________________________________________________________________________________________________________\r\n\r\n    def test_earth_relief_01d():\r\n        \"Test some properties of the earth relief 01d data\"\r\n        data = load_earth_relief(resolution=\"01d\")\r\n>       assert data.shape == (181, 361)\r\nE       assert (180, 360) == (181, 361)\r\nE         At index 0 diff: 180 != 181\r\nE         Full diff:\r\nE         - (181, 361)\r\nE         ?    ^    ^\r\nE         + (180, 360)\r\nE         ?    ^    ^\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_datasets.py:74: AssertionError\r\n______________________________________________________________________________________________________________________ test_earth_relief_30m ______________________________________________________________________________________________________________________\r\n\r\n    def test_earth_relief_30m():\r\n        \"Test some properties of the earth relief 30m data\"\r\n        data = load_earth_relief(resolution=\"30m\")\r\n>       assert data.shape == (361, 721)\r\nE       assert (360, 720) == (361, 721)\r\nE         At index 0 diff: 360 != 361\r\nE         Full diff:\r\nE         - (361, 721)\r\nE         ?    ^    ^\r\nE         + (360, 720)\r\nE         ?    ^    ^\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_datasets.py:84: AssertionError\r\n---------------------------------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------------------------------\r\ngmtwhich [NOTICE]: Remote data courtesy of GMT data server OCEANIA [https://oceania.generic-mapping-tools.org]\r\ngmtwhich [NOTICE]: Earth Relief at 30x30 arc minutes from Gaussian Cartesian filtering (55 km fullwidth) of SRTM15+V2.1 [Tozer et al., 2019].\r\ngmtwhich [NOTICE]:   -> Download grid file [395K]: earth_relief_30m_p.grd\r\n_________________________________________________________________________________________________________________________ test_grdcontour _________________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1795, 900)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpnta9dz9d/baseline-test_grdcontour.png\r\n  Actual shape: (1794, 902)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpnta9dz9d/test_grdcontour.png\r\n_____________________________________________________________________________________________________________________ test_grdcontour_labels ______________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1795, 900)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp7dtpwm5q/baseline-test_grdcontour_labels.png\r\n  Actual shape: (1794, 902)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp7dtpwm5q/test_grdcontour_labels.png\r\n______________________________________________________________________________________________________________________ test_grdcontour_slice ______________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1801, 313)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpxyc84zg6/baseline-test_grdcontour_slice.png\r\n  Actual shape: (1801, 309)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpxyc84zg6/test_grdcontour_slice.png\r\n______________________________________________________________________________________________________________________ test_grdcontour_file _______________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (3000, 1652)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpyik9d1ae/baseline-test_grdcontour_file.png\r\n  Actual shape: (2994, 1652)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpyik9d1ae/test_grdcontour_file.png\r\n_____________________________________________________________________________________________________________ test_grdcontour_interval_file_full_opts _____________________________________________________________________________________________________________\r\nError: Image files did not match.\r\n  RMS Value: 57.021765942941926\r\n  Expected:  \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmppcai0yyq/baseline-test_grdcontour_interval_file_full_opts.png\r\n  Actual:    \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmppcai0yyq/test_grdcontour_interval_file_full_opts.png\r\n  Difference:\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmppcai0yyq/test_grdcontour_interval_file_full_opts-failed-diff.png\r\n  Tolerance: \r\n    2\r\n__________________________________________________________________________________________________________________ test_grdcut_file_in_file_out ___________________________________________________________________________________________________________________\r\n\r\n    def test_grdcut_file_in_file_out():\r\n        \"grduct an input grid file, and output to a grid file\"\r\n        with GMTTempFile(suffix=\".nc\") as tmpfile:\r\n            result = grdcut(\"@earth_relief_01d\", outgrid=tmpfile.name, region=\"0/180/0/90\")\r\n            assert result is None  # return value is None\r\n            assert os.path.exists(path=tmpfile.name)  # check that outgrid exists\r\n            result = grdinfo(tmpfile.name, C=True)\r\n>           assert result == \"0 180 0 90 -8592.5 5559 1 1 181 91\\n\"\r\nE           AssertionError: assert '0 180 0 90 -8182 5651.5 1 1 180 90 1 1\\n' == '0 180 0 90 -8592.5 5559 1 1 181 91\\n'\r\nE             - 0 180 0 90 -8592.5 5559 1 1 181 91\r\nE             + 0 180 0 90 -8182 5651.5 1 1 180 90 1 1\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcut.py:22: AssertionError\r\n________________________________________________________________________________________________________________ test_grdcut_file_in_dataarray_out ________________________________________________________________________________________________________________\r\n\r\n    def test_grdcut_file_in_dataarray_out():\r\n        \"grdcut an input grid file, and output as DataArray\"\r\n        outgrid = grdcut(\"@earth_relief_01d\", region=\"0/180/0/90\")\r\n        assert isinstance(outgrid, xr.DataArray)\r\n        # check information of the output grid\r\n        # the '@earth_relief_01d' is in pixel registration, so the grid range is\r\n        # not exactly 0/180/0/90\r\n>       assert outgrid.coords[\"lat\"].data.min() == 0.0\r\nE       assert 0.5 == 0.0\r\nE         +0.5\r\nE         -0.0\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdcut.py:32: AssertionError\r\n__________________________________________________________________________________________________________________________ test_grdimage __________________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1800, 900)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpyab_pm_9/baseline-test_grdimage.png\r\n  Actual shape: (1800, 902)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpyab_pm_9/test_grdimage.png\r\n_______________________________________________________________________________________________________________________ test_grdimage_slice _______________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1800, 313)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp13aadxic/baseline-test_grdimage_slice.png\r\n  Actual shape: (1800, 309)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp13aadxic/test_grdimage_slice.png\r\n_______________________________________________________________________________________________________________________ test_grdimage_file ________________________________________________________________________________________________________________________\r\nError: Image files did not match.\r\n  RMS Value: 18.437474628436362\r\n  Expected:  \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpqf2fju2f/baseline-test_grdimage_file.png\r\n  Actual:    \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpqf2fju2f/test_grdimage_file.png\r\n  Difference:\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpqf2fju2f/test_grdimage_file-failed-diff.png\r\n  Tolerance: \r\n    2\r\n__________________________________________________________________________________________________________________________ test_grdinfo ___________________________________________________________________________________________________________________________\r\n\r\n    def test_grdinfo():\r\n        \"Make sure grd info works as expected\"\r\n        grid = load_earth_relief()\r\n        result = grdinfo(grid, L=0, C=\"n\")\r\n>       assert result.strip() == \"-180 180 -90 90 -8592.5 5559 1 1 361 181\"\r\nE       AssertionError: assert '-179.5 179.5 -89.5 89.5 -8182 5651.5 1 1 360 180 0 0' == '-180 180 -90 90 -8592.5 5559 1 1 361 181'\r\nE         - -180 180 -90 90 -8592.5 5559 1 1 361 181\r\nE         + -179.5 179.5 -89.5 89.5 -8182 5651.5 1 1 360 180 0 0\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdinfo.py:16: AssertionError\r\n________________________________________________________________________________________________________________________ test_grdinfo_file ________________________________________________________________________________________________________________________\r\n\r\n    def test_grdinfo_file():\r\n        \"Test grdinfo with file input\"\r\n        result = grdinfo(\"@earth_relief_01d\", L=0, C=\"n\")\r\n>       assert result.strip() == \"-180 180 -90 90 -8592.5 5559 1 1 361 181\"\r\nE       AssertionError: assert '-180 180 -90 90 -8182 5651.5 1 1 360 180 1 1' == '-180 180 -90 90 -8592.5 5559 1 1 361 181'\r\nE         - -180 180 -90 90 -8592.5 5559 1 1 361 181\r\nE         ?                    ^^   -----      ^\r\nE         + -180 180 -90 90 -8182 5651.5 1 1 360 180 1 1\r\nE         ?                   ++++ ^^^         ^   ++ ++\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdinfo.py:22: AssertionError\r\n___________________________________________________________________________________________________________ test_grdtrack_input_dataframe_and_dataarray ___________________________________________________________________________________________________________\r\n\r\n    def test_grdtrack_input_dataframe_and_dataarray():\r\n        \"\"\"\r\n        Run grdtrack by passing in a pandas.DataFrame and xarray.DataArray as\r\n        inputs\r\n        \"\"\"\r\n        dataframe = load_ocean_ridge_points()\r\n        dataarray = load_earth_relief().sel(lat=slice(-49, -42), lon=slice(-118, -107))\r\n    \r\n        output = grdtrack(points=dataframe, grid=dataarray, newcolname=\"bathymetry\")\r\n        assert isinstance(output, pd.DataFrame)\r\n        assert output.columns.to_list() == [\"longitude\", \"latitude\", \"bathymetry\"]\r\n>       npt.assert_allclose(output.iloc[0], [-110.9536, -42.2489, -2797.394987])\r\nE       AssertionError: \r\nE       Not equal to tolerance rtol=1e-07, atol=0\r\nE       \r\nE       Mismatched elements: 3 / 3 (100%)\r\nE       Max absolute difference: 4050953.226623\r\nE       Max relative difference: 1448.11628156\r\nE        x: array([-1.117309e+02, -4.317060e+01, -4.053751e+06])\r\nE        y: array([ -110.9536  ,   -42.2489  , -2797.394987])\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdtrack.py:31: AssertionError\r\n---------------------------------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------------------------------\r\ngrdtrack [WARNING]: Some input points were outside the grid domain(s).\r\n____________________________________________________________________________________________________________ test_grdtrack_input_csvfile_and_dataarray ____________________________________________________________________________________________________________\r\n\r\n    def test_grdtrack_input_csvfile_and_dataarray():\r\n        \"\"\"\r\n        Run grdtrack by passing in a csvfile and xarray.DataArray as inputs\r\n        \"\"\"\r\n        csvfile = which(\"@ridge.txt\", download=\"c\")\r\n        dataarray = load_earth_relief().sel(lat=slice(-49, -42), lon=slice(-118, -107))\r\n    \r\n        try:\r\n            output = grdtrack(points=csvfile, grid=dataarray, outfile=TEMP_TRACK)\r\n            assert output is None  # check that output is None since outfile is set\r\n            assert os.path.exists(path=TEMP_TRACK)  # check that outfile exists at path\r\n    \r\n            track = pd.read_csv(TEMP_TRACK, sep=\"\\t\", header=None, comment=\">\")\r\n>           npt.assert_allclose(track.iloc[0], [-110.9536, -42.2489, -2797.394987])\r\nE           AssertionError: \r\nE           Not equal to tolerance rtol=1e-07, atol=0\r\nE           \r\nE           Mismatched elements: 3 / 3 (100%)\r\nE           Max absolute difference: 3.77560601e+22\r\nE           Max relative difference: 1.34968642e+19\r\nE            x: array([-1.117309e+02, -4.317060e+01, -3.775606e+22])\r\nE            y: array([ -110.9536  ,   -42.2489  , -2797.394987])\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdtrack.py:49: AssertionError\r\n---------------------------------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------------------------------\r\ngrdtrack [WARNING]: Some input points were outside the grid domain(s).\r\n____________________________________________________________________________________________________________ test_grdtrack_input_dataframe_and_ncfile _____________________________________________________________________________________________________________\r\n\r\n    def test_grdtrack_input_dataframe_and_ncfile():\r\n        \"\"\"\r\n        Run grdtrack by passing in a pandas.DataFrame and netcdf file as inputs\r\n        \"\"\"\r\n        dataframe = load_ocean_ridge_points()\r\n        ncfile = which(\"@earth_relief_01d\", download=\"c\")\r\n    \r\n        output = grdtrack(points=dataframe, grid=ncfile, newcolname=\"bathymetry\")\r\n        assert isinstance(output, pd.DataFrame)\r\n        assert output.columns.to_list() == [\"longitude\", \"latitude\", \"bathymetry\"]\r\n>       npt.assert_allclose(output.iloc[0], [-32.2971, 37.4118, -1686.748899])\r\nE       AssertionError: \r\nE       Not equal to tolerance rtol=1e-07, atol=0\r\nE       \r\nE       Mismatched elements: 1 / 3 (33.3%)\r\nE       Max absolute difference: 252.99934649\r\nE       Max relative difference: 0.1499923\r\nE        x: array([  -32.2971  ,    37.4118  , -1939.748245])\r\nE        y: array([  -32.2971  ,    37.4118  , -1686.748899])\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdtrack.py:66: AssertionError\r\n_____________________________________________________________________________________________________________ test_grdtrack_input_csvfile_and_ncfile ______________________________________________________________________________________________________________\r\n\r\n    def test_grdtrack_input_csvfile_and_ncfile():\r\n        \"\"\"\r\n        Run grdtrack by passing in a csvfile and netcdf file as inputs\r\n        \"\"\"\r\n        csvfile = which(\"@ridge.txt\", download=\"c\")\r\n        ncfile = which(\"@earth_relief_01d\", download=\"c\")\r\n    \r\n        try:\r\n            output = grdtrack(points=csvfile, grid=ncfile, outfile=TEMP_TRACK)\r\n            assert output is None  # check that output is None since outfile is set\r\n            assert os.path.exists(path=TEMP_TRACK)  # check that outfile exists at path\r\n    \r\n            track = pd.read_csv(TEMP_TRACK, sep=\"\\t\", header=None, comment=\">\")\r\n>           npt.assert_allclose(track.iloc[0], [-32.2971, 37.4118, -1686.748899])\r\nE           AssertionError: \r\nE           Not equal to tolerance rtol=1e-07, atol=0\r\nE           \r\nE           Mismatched elements: 1 / 3 (33.3%)\r\nE           Max absolute difference: 252.99934649\r\nE           Max relative difference: 0.1499923\r\nE            x: array([  -32.2971  ,    37.4118  , -1939.748245])\r\nE            y: array([  -32.2971  ,    37.4118  , -1686.748899])\r\n\r\n/Users/locupe/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/tests/test_grdtrack.py:84: AssertionError\r\n___________________________________________________________________________________________________________________ test_grdview_grid_dataarray ___________________________________________________________________________________________________________________\r\nError: Image files did not match.\r\n  RMS Value: 40.16190604322967\r\n  Expected:  \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpn46juxbg/baseline-test_grdview_grid_dataarray.png\r\n  Actual:    \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpn46juxbg/test_grdview_grid_dataarray.png\r\n  Difference:\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpn46juxbg/test_grdview_grid_dataarray-failed-diff.png\r\n  Tolerance: \r\n    2\r\n____________________________________________________________________________________________________________ test_grdview_grid_file_with_region_subset ____________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1772, 1772)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmptmasslyu/baseline-test_grdview_grid_file_with_region_subset.png\r\n  Actual shape: (1772, 760)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmptmasslyu/test_grdview_grid_file_with_region_subset.png\r\n__________________________________________________________________________________________________________________ test_grdview_with_perspective __________________________________________________________________________________________________________________\r\nError: Image files did not match.\r\n  RMS Value: 49.520272872052345\r\n  Expected:  \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpe49fxcp9/baseline-test_grdview_with_perspective.png\r\n  Actual:    \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpe49fxcp9/test_grdview_with_perspective.png\r\n  Difference:\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpe49fxcp9/test_grdview_with_perspective-failed-diff.png\r\n  Tolerance: \r\n    2\r\n____________________________________________________________________________________________________________ test_grdview_with_perspective_and_zscale _____________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (2507, 1359)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpbak1ehxa/baseline-test_grdview_with_perspective_and_zscale.png\r\n  Actual shape: (2507, 1341)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpbak1ehxa/test_grdview_with_perspective_and_zscale.png\r\n_____________________________________________________________________________________________________________ test_grdview_with_perspective_and_zsize _____________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (2507, 1566)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpcvze31pd/baseline-test_grdview_with_perspective_and_zsize.png\r\n  Actual shape: (2507, 1555)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpcvze31pd/test_grdview_with_perspective_and_zsize.png\r\n______________________________________________________________________________________________________________ test_grdview_with_cmap_for_image_plot ______________________________________________________________________________________________________________\r\nError: Image files did not match.\r\n  RMS Value: 82.90239290987333\r\n  Expected:  \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmphiwwtef5/baseline-test_grdview_with_cmap_for_image_plot.png\r\n  Actual:    \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmphiwwtef5/test_grdview_with_cmap_for_image_plot.png\r\n  Difference:\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmphiwwtef5/test_grdview_with_cmap_for_image_plot-failed-diff.png\r\n  Tolerance: \r\n    2\r\n_______________________________________________________________________________________________________ test_grdview_with_cmap_for_surface_monochrome_plot ________________________________________________________________________________________________________\r\nError: Image files did not match.\r\n  RMS Value: 71.67456522119535\r\n  Expected:  \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpumox916_/baseline-test_grdview_with_cmap_for_surface_monochrome_plot.png\r\n  Actual:    \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpumox916_/test_grdview_with_cmap_for_surface_monochrome_plot.png\r\n  Difference:\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpumox916_/test_grdview_with_cmap_for_surface_monochrome_plot-failed-diff.png\r\n  Tolerance: \r\n    2\r\n_______________________________________________________________________________________________________ test_grdview_with_cmap_for_perspective_surface_plot _______________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (2506, 1358)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpvnf10u9h/baseline-test_grdview_with_cmap_for_perspective_surface_plot.png\r\n  Actual shape: (2506, 1340)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpvnf10u9h/test_grdview_with_cmap_for_perspective_surface_plot.png\r\n_____________________________________________________________________________________________________________________ test_grdview_on_a_plane _____________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (2509, 1675)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp5mi614b3/baseline-test_grdview_on_a_plane.png\r\n  Actual shape: (2509, 1691)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp5mi614b3/test_grdview_on_a_plane.png\r\n_______________________________________________________________________________________________________ test_grdview_on_a_plane_with_colored_frontal_facade _______________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (2509, 1676)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp_ku0tx8u/baseline-test_grdview_on_a_plane_with_colored_frontal_facade.png\r\n  Actual shape: (2509, 1692)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp_ku0tx8u/test_grdview_on_a_plane_with_colored_frontal_facade.png\r\n__________________________________________________________________________________________________________ test_grdview_with_perspective_and_zaxis_frame __________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (2566, 1636)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpokoupyvh/baseline-test_grdview_with_perspective_and_zaxis_frame.png\r\n  Actual shape: (2566, 1626)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpokoupyvh/test_grdview_with_perspective_and_zaxis_frame.png\r\n________________________________________________________________________________________________________ test_grdview_surface_plot_styled_with_contourpen _________________________________________________________________________________________________________\r\nError: Image files did not match.\r\n  RMS Value: 95.81921012966873\r\n  Expected:  \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpeipjeyk9/baseline-test_grdview_surface_plot_styled_with_contourpen.png\r\n  Actual:    \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpeipjeyk9/test_grdview_surface_plot_styled_with_contourpen.png\r\n  Difference:\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpeipjeyk9/test_grdview_surface_plot_styled_with_contourpen-failed-diff.png\r\n  Tolerance: \r\n    2\r\n_______________________________________________________________________________________________________ test_grdview_surface_mesh_plot_styled_with_meshpen ________________________________________________________________________________________________________\r\nError: Image files did not match.\r\n  RMS Value: 95.72615837162644\r\n  Expected:  \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmph7da99u3/baseline-test_grdview_surface_mesh_plot_styled_with_meshpen.png\r\n  Actual:    \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmph7da99u3/test_grdview_surface_mesh_plot_styled_with_meshpen.png\r\n  Difference:\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmph7da99u3/test_grdview_surface_mesh_plot_styled_with_meshpen-failed-diff.png\r\n  Tolerance: \r\n    2\r\n__________________________________________________________________________________________________________ test_grdview_on_a_plane_styled_with_facadepen __________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (2508, 1674)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp1ghut5fh/baseline-test_grdview_on_a_plane_styled_with_facadepen.png\r\n  Actual shape: (2508, 1690)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp1ghut5fh/test_grdview_on_a_plane_styled_with_facadepen.png\r\n________________________________________________________________________________________________________________ test_grdview_drapegrid_dataarray _________________________________________________________________________________________________________________\r\nError: Image files did not match.\r\n  RMS Value: 61.18795003636725\r\n  Expected:  \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp5vncaj_d/baseline-test_grdview_drapegrid_dataarray.png\r\n  Actual:    \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp5vncaj_d/test_grdview_drapegrid_dataarray.png\r\n  Difference:\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp5vncaj_d/test_grdview_drapegrid_dataarray-failed-diff.png\r\n  Tolerance: \r\n    2\r\n_______________________________________________________________________________________________________________________ test_legend_entries _______________________________________________________________________________________________________________________\r\nError: Image files did not match.\r\n  RMS Value: 3.7333930043449666\r\n  Expected:  \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpuphow1kw/baseline-test_legend_entries.png\r\n  Actual:    \r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpuphow1kw/test_legend_entries.png\r\n  Difference:\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpuphow1kw/test_legend_entries-failed-diff.png\r\n  Tolerance: \r\n    2\r\n____________________________________________________________________________________________________________________ test_makecpt_to_plot_grid ____________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1800, 900)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp8iu7mk5f/baseline-test_makecpt_to_plot_grid.png\r\n  Actual shape: (1800, 902)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp8iu7mk5f/test_makecpt_to_plot_grid.png\r\n__________________________________________________________________________________________________________ test_makecpt_to_plot_grid_scaled_with_series ___________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1800, 900)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpari24ju5/baseline-test_makecpt_to_plot_grid_scaled_with_series.png\r\n  Actual shape: (1800, 902)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpari24ju5/test_makecpt_to_plot_grid_scaled_with_series.png\r\n______________________________________________________________________________________________________________ test_makecpt_truncated_to_zlow_zhigh _______________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1800, 900)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpes95r11c/baseline-test_makecpt_truncated_to_zlow_zhigh.png\r\n  Actual shape: (1800, 902)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpes95r11c/test_makecpt_truncated_to_zlow_zhigh.png\r\n_______________________________________________________________________________________________________________ test_makecpt_truncated_at_zlow_only _______________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1800, 900)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpzi1dbpx5/baseline-test_makecpt_truncated_at_zlow_only.png\r\n  Actual shape: (1800, 902)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpzi1dbpx5/test_makecpt_truncated_at_zlow_only.png\r\n______________________________________________________________________________________________________________ test_makecpt_truncated_at_zhigh_only _______________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1800, 900)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp_w0sn3xo/baseline-test_makecpt_truncated_at_zhigh_only.png\r\n  Actual shape: (1800, 902)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp_w0sn3xo/test_makecpt_truncated_at_zhigh_only.png\r\n_________________________________________________________________________________________________________________ test_makecpt_reverse_color_only _________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1800, 900)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpuae7cclp/baseline-test_makecpt_reverse_color_only.png\r\n  Actual shape: (1800, 902)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpuae7cclp/test_makecpt_reverse_color_only.png\r\n_________________________________________________________________________________________________________________ test_makecpt_reverse_zsign_only _________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1800, 900)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmptkwa_fbv/baseline-test_makecpt_reverse_zsign_only.png\r\n  Actual shape: (1800, 902)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmptkwa_fbv/test_makecpt_reverse_zsign_only.png\r\n______________________________________________________________________________________________________________ test_makecpt_reverse_color_and_zsign _______________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1800, 900)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp2pe_d_o5/baseline-test_makecpt_reverse_color_and_zsign.png\r\n  Actual shape: (1800, 902)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmp2pe_d_o5/test_makecpt_reverse_color_and_zsign.png\r\n_____________________________________________________________________________________________________________________ test_makecpt_continuous _____________________________________________________________________________________________________________________\r\nError: Image dimensions did not match.\r\n  Expected shape: (1800, 900)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpdq63tcfv/baseline-test_makecpt_continuous.png\r\n  Actual shape: (1800, 902)\r\n    /var/folders/_3/9z9zj5090_b341bkc7cw74cr0000gq/T/tmpdq63tcfv/test_makecpt_continuous.png\r\n===================================================================================================================== short test summary info =====================================================================================================================\r\nFAILED clib/conversion.py::pygmt.clib.conversion.dataarray_to_matrix\r\nFAILED clib/session.py::pygmt.clib.session.Session\r\nFAILED clib/session.py::pygmt.clib.session.Session.virtualfile_from_grid\r\nFAILED tests/test_basemap.py::test_basemap_polar\r\nFAILED tests/test_clib.py::test_call_module_error_message - assert (\"Module 'info' failed with status code 71:\\n\"\\n 'gmtinfo [ERROR]: Cannot find file bogus-data.bla') == (\"Module 'info' failed with status code 71:\\n\"\\n 'gmtinfo [ERROR]: Error for input fi...\r\nFAILED tests/test_coast.py::test_coast_iceland\r\nFAILED tests/test_colorbar.py::test_colorbar_positioned_using_justification_code\r\nFAILED tests/test_config.py::test_config\r\nFAILED tests/test_config.py::test_config_font_one\r\nFAILED tests/test_config.py::test_config_font_annot\r\nFAILED tests/test_datasets.py::test_earth_relief_01d - assert (180, 360) == (181, 361)\r\nFAILED tests/test_datasets.py::test_earth_relief_30m - assert (360, 720) == (361, 721)\r\nFAILED tests/test_grdcontour.py::test_grdcontour\r\nFAILED tests/test_grdcontour.py::test_grdcontour_labels\r\nFAILED tests/test_grdcontour.py::test_grdcontour_slice\r\nFAILED tests/test_grdcontour.py::test_grdcontour_file\r\nFAILED tests/test_grdcontour.py::test_grdcontour_interval_file_full_opts\r\nFAILED tests/test_grdcut.py::test_grdcut_file_in_file_out - AssertionError: assert '0 180 0 90 -8182 5651.5 1 1 180 90 1 1\\n' == '0 180 0 90 -8592.5 5559 1 1 181 91\\n'\r\nFAILED tests/test_grdcut.py::test_grdcut_file_in_dataarray_out - assert 0.5 == 0.0\r\nFAILED tests/test_grdimage.py::test_grdimage\r\nFAILED tests/test_grdimage.py::test_grdimage_slice\r\nFAILED tests/test_grdimage.py::test_grdimage_file\r\nFAILED tests/test_grdinfo.py::test_grdinfo - AssertionError: assert '-179.5 179.5 -89.5 89.5 -8182 5651.5 1 1 360 180 0 0' == '-180 180 -90 90 -8592.5 5559 1 1 361 181'\r\nFAILED tests/test_grdinfo.py::test_grdinfo_file - AssertionError: assert '-180 180 -90 90 -8182 5651.5 1 1 360 180 1 1' == '-180 180 -90 90 -8592.5 5559 1 1 361 181'\r\nFAILED tests/test_grdtrack.py::test_grdtrack_input_dataframe_and_dataarray - AssertionError: \r\nFAILED tests/test_grdtrack.py::test_grdtrack_input_csvfile_and_dataarray - AssertionError: \r\nFAILED tests/test_grdtrack.py::test_grdtrack_input_dataframe_and_ncfile - AssertionError: \r\nFAILED tests/test_grdtrack.py::test_grdtrack_input_csvfile_and_ncfile - AssertionError: \r\nFAILED tests/test_grdview.py::test_grdview_grid_dataarray\r\nFAILED tests/test_grdview.py::test_grdview_grid_file_with_region_subset\r\nFAILED tests/test_grdview.py::test_grdview_with_perspective\r\nFAILED tests/test_grdview.py::test_grdview_with_perspective_and_zscale\r\nFAILED tests/test_grdview.py::test_grdview_with_perspective_and_zsize\r\nFAILED tests/test_grdview.py::test_grdview_with_cmap_for_image_plot\r\nFAILED tests/test_grdview.py::test_grdview_with_cmap_for_surface_monochrome_plot\r\nFAILED tests/test_grdview.py::test_grdview_with_cmap_for_perspective_surface_plot\r\nFAILED tests/test_grdview.py::test_grdview_on_a_plane\r\nFAILED tests/test_grdview.py::test_grdview_on_a_plane_with_colored_frontal_facade\r\nFAILED tests/test_grdview.py::test_grdview_with_perspective_and_zaxis_frame\r\nFAILED tests/test_grdview.py::test_grdview_surface_plot_styled_with_contourpen\r\nFAILED tests/test_grdview.py::test_grdview_surface_mesh_plot_styled_with_meshpen\r\nFAILED tests/test_grdview.py::test_grdview_on_a_plane_styled_with_facadepen\r\nFAILED tests/test_grdview.py::test_grdview_drapegrid_dataarray\r\nFAILED tests/test_legend.py::test_legend_entries\r\nFAILED tests/test_makecpt.py::test_makecpt_to_plot_grid\r\nFAILED tests/test_makecpt.py::test_makecpt_to_plot_grid_scaled_with_series\r\nFAILED tests/test_makecpt.py::test_makecpt_truncated_to_zlow_zhigh\r\nFAILED tests/test_makecpt.py::test_makecpt_truncated_at_zlow_only\r\nFAILED tests/test_makecpt.py::test_makecpt_truncated_at_zhigh_only\r\nFAILED tests/test_makecpt.py::test_makecpt_reverse_color_only\r\nFAILED tests/test_makecpt.py::test_makecpt_reverse_zsign_only\r\nFAILED tests/test_makecpt.py::test_makecpt_reverse_color_and_zsign\r\nFAILED tests/test_makecpt.py::test_makecpt_continuous\r\n====================================================================================================== 53 failed, 212 passed, 1 skipped in 94.31s (0:01:34) =======================================================================================================\r\n---------------------------------------------------------------------------\r\nAssertionError                            Traceback (most recent call last)\r\n<ipython-input-2-3b88ed9e84c1> in <module>\r\n----> 1 pygmt.test()\r\n\r\n~/anaconda2/envs/pygmt/lib/python3.8/site-packages/pygmt/__init__.py in test(doctest, verbose, coverage, figures)\r\n    185     args.append(package)\r\n    186     status = pytest.main(args)\r\n--> 187     assert status == 0, \"Some tests have failed.\"\r\n\r\nAssertionError: Some tests have failed.\r\n\r\n```\r\n</details>\r\n\r\n\r\n\r\n## System information\r\n\r\nPlease paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`:\r\n\r\n```\r\n python -c \"import pygmt; pygmt.show_versions()\"                                                                                                                                                                                                \u272d 14:56:44\r\nPyGMT information:\r\n  version: v0.1.2\r\nSystem information:\r\n  python: 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:21:09)  [Clang 9.0.1 ]\r\n  executable: /Users/locupe/anaconda2/envs/pygmt/bin/python\r\n  machine: macOS-10.15.5-x86_64-i386-64bit\r\nDependency information:\r\n  numpy: 1.18.5\r\n  pandas: 1.0.5\r\n  xarray: 0.15.1\r\n  netCDF4: 1.5.3\r\n  packaging: 20.4\r\n  ghostscript: 9.22\r\n  gmt: 6.1.0\r\nGMT library information:\r\n  binary dir: /Users/locupe/anaconda2/envs/pygmt/bin\r\n  cores: 12\r\n  grid layout: rows\r\n  library path: /Users/locupe/anaconda2/envs/pygmt/lib/libgmt.dylib\r\n  padding: 2\r\n  plugin dir: /Users/locupe/anaconda2/envs/pygmt/lib/gmt/plugins\r\n  share dir: /Users/locupe/anaconda2/envs/pygmt/share/gmt\r\n  version: 6.1.0\r\n```\r\n",
    "closed_at": "2020-09-12T21:31:34Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
        "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
        "followers_url": "https://api.github.com/users/weiji14/followers",
        "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
        "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/weiji14",
        "id": 23487320,
        "login": "weiji14",
        "node_id": "MDQ6VXNlcjIzNDg3MzIw",
        "organizations_url": "https://api.github.com/users/weiji14/orgs",
        "received_events_url": "https://api.github.com/users/weiji14/received_events",
        "repos_url": "https://api.github.com/users/weiji14/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/weiji14"
    },
    "comments": 7,
    "comments_content": [
        {
            "author_association": "NONE",
            "body": "\ud83d\udc4b Thanks for opening your first issue here! Please make sure you filled out the template with as much detail as possible. You might also want to take a look at our [contributing guidelines](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/GenericMappingTools/pygmt/blob/master/CODE_OF_CONDUCT.md).\n",
            "created_at": "2020-07-08T14:07:21Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/508#issuecomment-655543203",
            "id": 655543203,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/508",
            "node_id": "MDEyOklzc3VlQ29tbWVudDY1NTU0MzIwMw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/655543203/reactions"
            },
            "updated_at": "2020-07-08T14:07:21Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/655543203",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/in/4141?v=4",
                "events_url": "https://api.github.com/users/welcome%5Bbot%5D/events{/privacy}",
                "followers_url": "https://api.github.com/users/welcome%5Bbot%5D/followers",
                "following_url": "https://api.github.com/users/welcome%5Bbot%5D/following{/other_user}",
                "gists_url": "https://api.github.com/users/welcome%5Bbot%5D/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/apps/welcome",
                "id": 30606887,
                "login": "welcome[bot]",
                "node_id": "MDM6Qm90MzA2MDY4ODc=",
                "organizations_url": "https://api.github.com/users/welcome%5Bbot%5D/orgs",
                "received_events_url": "https://api.github.com/users/welcome%5Bbot%5D/received_events",
                "repos_url": "https://api.github.com/users/welcome%5Bbot%5D/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/welcome%5Bbot%5D/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/welcome%5Bbot%5D/subscriptions",
                "type": "Bot",
                "url": "https://api.github.com/users/welcome%5Bbot%5D"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Hi @lhoupert, thanks for reporting this issue and filling up the template in such detail! We're aware of the 53 test failures, and you'll notice that most of them are `grd*` related. It's to do with the change in the default `earth_relief` grids from **gridline** registered to **pixel** registered when going from GMT 6.0 to 6.1 (our tests were built on GMT 6.0). See also https://forum.generic-mapping-tools.org/t/about-pygmt-test/598 and the disclaimer on https://forum.generic-mapping-tools.org/t/pygmt-v0-1-2-released/629/1.\r\n\r\nWe're working on a fix at #507, but in the meantime, you have a few options:\r\n\r\n1. Stay on GMT 6.1, ignore the test failures, and wait for the bugfix to come in [v0.2.0](https://github.com/GenericMappingTools/pygmt/milestone/2).\r\n2. Downgrade to GMT 6.0, which will mean no test failures, but do realize that there are some issues with this (see point below).\r\n\r\nNote that PyGMT incorrectly assumes *all* `xarray` grids to be gridline registered with Cartesian coordinates by default (rather than pixel registered with Geographic coordinates). If you're plotting grids, I would strongly recommend passing them in as filenames (e.g. `climatedata.nc`) instead of as `xarray.DataArray` grids at the moment. You may also be interested in reading the discussion at #487 to find out more. Let us know if you need more clarification.",
            "created_at": "2020-07-08T22:13:56Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/508#issuecomment-655785330",
            "id": 655785330,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/508",
            "node_id": "MDEyOklzc3VlQ29tbWVudDY1NTc4NTMzMA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/655785330/reactions"
            },
            "updated_at": "2020-07-08T22:13:56Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/655785330",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "Thank you @weiji14 for your quick reply!\r\n\r\nIf I stay with my current version *GMT 6.1.0*, does it mean I will not be able to use the ```grd* ``` function? \r\n\r\nI would like to run the code below in pygmt, is it possible? \r\n```code \r\ntopo_grd=\"@earth_relief_06m.grd\"\r\ngmt grd2cpt $topo_grd -Cglobe -L-500/7000 -T-500/7000/20 -Z > topo.cpt\r\n```",
            "created_at": "2020-07-09T09:45:35Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/508#issuecomment-656027462",
            "id": 656027462,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/508",
            "node_id": "MDEyOklzc3VlQ29tbWVudDY1NjAyNzQ2Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/656027462/reactions"
            },
            "updated_at": "2020-07-09T09:45:35Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/656027462",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10154151?v=4",
                "events_url": "https://api.github.com/users/lhoupert/events{/privacy}",
                "followers_url": "https://api.github.com/users/lhoupert/followers",
                "following_url": "https://api.github.com/users/lhoupert/following{/other_user}",
                "gists_url": "https://api.github.com/users/lhoupert/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/lhoupert",
                "id": 10154151,
                "login": "lhoupert",
                "node_id": "MDQ6VXNlcjEwMTU0MTUx",
                "organizations_url": "https://api.github.com/users/lhoupert/orgs",
                "received_events_url": "https://api.github.com/users/lhoupert/received_events",
                "repos_url": "https://api.github.com/users/lhoupert/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/lhoupert/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lhoupert/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/lhoupert"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> If I stay with my current version _GMT 6.1.0_, does it mean I will not be able to use the `grd* ` function?\r\n\r\nYou *can* still use it, it should be okay if you pass in filenames as input, rather than xarray grids (which has buggy behaviour). I.e. `grdimage(\"earth_relief_06m.grd\")` is good, `grdimage(xr.open_dataarray(\"earth_relief_06m.grd\"))` is bad.\r\n\r\n> I would like to run the code below in pygmt, is it possible?\r\n> \r\n> ```\r\n> topo_grd=\"@earth_relief_06m.grd\"\r\n> gmt grd2cpt $topo_grd -Cglobe -L-500/7000 -T-500/7000/20 -Z > topo.cpt\r\n> ```\r\n\r\nWell, we haven't implemented `grd2cpt` yet, only [`makecpt`](https://www.pygmt.org/v0.1.2/api/generated/pygmt.makecpt.html). I'd be keen to see it in PyGMT though, would you mind opening a feature request for it? :smile:",
            "created_at": "2020-07-09T09:54:00Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/508#issuecomment-656031189",
            "id": 656031189,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/508",
            "node_id": "MDEyOklzc3VlQ29tbWVudDY1NjAzMTE4OQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/656031189/reactions"
            },
            "updated_at": "2020-07-09T09:54:00Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/656031189",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "Great thank you I will explore pygmt for a little bit before asking new features :-D ",
            "created_at": "2020-07-09T10:15:11Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/508#issuecomment-656040920",
            "id": 656040920,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/508",
            "node_id": "MDEyOklzc3VlQ29tbWVudDY1NjA0MDkyMA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/656040920/reactions"
            },
            "updated_at": "2020-07-09T10:15:20Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/656040920",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10154151?v=4",
                "events_url": "https://api.github.com/users/lhoupert/events{/privacy}",
                "followers_url": "https://api.github.com/users/lhoupert/followers",
                "following_url": "https://api.github.com/users/lhoupert/following{/other_user}",
                "gists_url": "https://api.github.com/users/lhoupert/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/lhoupert",
                "id": 10154151,
                "login": "lhoupert",
                "node_id": "MDQ6VXNlcjEwMTU0MTUx",
                "organizations_url": "https://api.github.com/users/lhoupert/orgs",
                "received_events_url": "https://api.github.com/users/lhoupert/received_events",
                "repos_url": "https://api.github.com/users/lhoupert/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/lhoupert/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lhoupert/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/lhoupert"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Hi @lhoupert, we've just released PyGMT v0.2.0 (see https://forum.generic-mapping-tools.org/t/pygmt-v0-2-0-released/879). Sorry that this took a while, but the test failures should be gone now, and the xarray grid plotting should more or less work (but do upgrade to GMT 6.1.1 first).\r\n\r\nFeel free to open up other feature requests/bug reports if you see that something is amiss. Have a great day :smile:",
            "created_at": "2020-09-12T21:31:20Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/508#issuecomment-691552617",
            "id": 691552617,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/508",
            "node_id": "MDEyOklzc3VlQ29tbWVudDY5MTU1MjYxNw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/691552617/reactions"
            },
            "updated_at": "2020-09-12T21:31:20Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/691552617",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "Great! Thank you for your work on this. I will give it another try when I\nam back on pygmt!\n\nLe sam. 12 sept. 2020 \u00e0 22:31, Wei Ji <notifications@github.com> a \u00e9crit :\n\n> Hi @lhoupert <https://github.com/lhoupert>, we've just released PyGMT\n> v0.2.0 (see\n> https://forum.generic-mapping-tools.org/t/pygmt-v0-2-0-released/879).\n> Sorry that this took a while, but the test failures should be gone now, and\n> the xarray grid plotting should more or less work (but do upgrade to GMT\n> 6.1.1 first).\n>\n> Feel free to open up other feature requests/bug reports if you see that\n> something is amiss. Have a great day \ud83d\ude04\n>\n> \u2014\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/GenericMappingTools/pygmt/issues/508#issuecomment-691552617>,\n> or unsubscribe\n> <https://github.com/notifications/unsubscribe-auth/ACNPBJYSG7YXD4G24P4OAV3SFPSDLANCNFSM4OUTPD4A>\n> .\n>\n",
            "created_at": "2020-09-15T07:46:51Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/508#issuecomment-692532941",
            "id": 692532941,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/508",
            "node_id": "MDEyOklzc3VlQ29tbWVudDY5MjUzMjk0MQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/692532941/reactions"
            },
            "updated_at": "2020-09-15T07:46:51Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/692532941",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10154151?v=4",
                "events_url": "https://api.github.com/users/lhoupert/events{/privacy}",
                "followers_url": "https://api.github.com/users/lhoupert/followers",
                "following_url": "https://api.github.com/users/lhoupert/following{/other_user}",
                "gists_url": "https://api.github.com/users/lhoupert/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/lhoupert",
                "id": 10154151,
                "login": "lhoupert",
                "node_id": "MDQ6VXNlcjEwMTU0MTUx",
                "organizations_url": "https://api.github.com/users/lhoupert/orgs",
                "received_events_url": "https://api.github.com/users/lhoupert/received_events",
                "repos_url": "https://api.github.com/users/lhoupert/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/lhoupert/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lhoupert/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/lhoupert"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/508/comments",
    "created_at": "2020-07-08T14:07:16Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/508/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/508",
    "id": 653328184,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/508/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": "2020-09-17T21:25:23Z",
        "closed_issues": 55,
        "created_at": "2020-04-16T23:17:22Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
            "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
            "followers_url": "https://api.github.com/users/weiji14/followers",
            "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
            "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/weiji14",
            "id": 23487320,
            "login": "weiji14",
            "node_id": "MDQ6VXNlcjIzNDg3MzIw",
            "organizations_url": "https://api.github.com/users/weiji14/orgs",
            "received_events_url": "https://api.github.com/users/weiji14/received_events",
            "repos_url": "https://api.github.com/users/weiji14/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/weiji14"
        },
        "description": "Bump minimum required GMT version to 6.1.1 or newer (#577). Ensure plotting xarray grids doesn't crash anymore and works for most cases (#560). Support datetime-like inputs to pygmt.plot (#464) and the region argument (#562).",
        "due_on": "2020-09-11T07:00:00Z",
        "html_url": "https://github.com/GenericMappingTools/pygmt/milestone/2",
        "id": 5318234,
        "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/2/labels",
        "node_id": "MDk6TWlsZXN0b25lNTMxODIzNA==",
        "number": 2,
        "open_issues": 0,
        "state": "closed",
        "title": "0.2.0",
        "updated_at": "2020-10-23T22:19:37Z",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/2"
    },
    "node_id": "MDU6SXNzdWU2NTMzMjgxODQ=",
    "number": 508,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/508/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/508/timeline",
    "title": "*pygmt.test()*  test failures on GMT 6.1.0",
    "updated_at": "2020-09-15T07:46:51Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/508",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/10154151?v=4",
        "events_url": "https://api.github.com/users/lhoupert/events{/privacy}",
        "followers_url": "https://api.github.com/users/lhoupert/followers",
        "following_url": "https://api.github.com/users/lhoupert/following{/other_user}",
        "gists_url": "https://api.github.com/users/lhoupert/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/lhoupert",
        "id": 10154151,
        "login": "lhoupert",
        "node_id": "MDQ6VXNlcjEwMTU0MTUx",
        "organizations_url": "https://api.github.com/users/lhoupert/orgs",
        "received_events_url": "https://api.github.com/users/lhoupert/received_events",
        "repos_url": "https://api.github.com/users/lhoupert/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/lhoupert/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lhoupert/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/lhoupert"
    }
}