{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "**Description of the problem**\r\n\r\nI am trying to use the BlockMean function, which works fine when I don't specify any projection. However, when I specify certain projections (e.g. I use M4i), certain datapoints are excluded in the Mean calculations. On the attached pictures it can be seen that a lot of my datapoints don't generate a mean value. \r\n\r\nIf anyone knows how to fix it, that would be amazing! \r\nThanks in advance.\r\n\r\n**Full code that generated the error**\r\n\r\n```python\r\npath = \"...\"\r\ninsar = pd.read_csv(path, delim_whitespace=True)\r\n\r\nif path[48:51] == 'vel':\r\n    data3 = \"vel\"\r\n    subtext = \"velocity [m/yr]\"\r\nelse: \r\n    data3 = \"displ\"\r\n    subtext = \"displacement [m]\"\r\n\r\ndata = insar[[\"long\", \"lat\",data3]]\r\n\r\n# Set the region for the plot\r\nregion = [-22.749375, -22.609891, 63.793357, 63.86]\r\n#region = [-22.7343772,-22.6408409, 63.802192,63.8486304] \r\n\r\n# Define spacing in x and y direction (150 by 150 minute blocks)\r\nspacing = '0.093k/0.105k'\r\n\r\nfig = pygmt.Figure()\r\n\r\ndf = pygmt.blockmean(data=data, region=region, spacing=spacing)\r\n\r\n# convert to grid\r\ngrd = pygmt.xyz2grd(data=df, region=region, spacing=spacing)\r\n\r\nprojection = None     #or \"M4i\"\r\n\r\nfig.grdimage(\r\n    projection=projection,\r\n    grid=grd,\r\n    region=[-22.749375, -22.609891, 63.793357, 63.86],\r\n    frame=[\"af\", '+t\"%s - %s\"'%(title1, title2)],\r\n    cmap=\"haxby\",\r\n)\r\n\r\nfig.plot(projection=projection,\r\n    x=data.long, y=data.lat, style=\"c0.05c\", color=\"white\", pen=\"0.1p,black\"\r\n)\r\n```\r\n\r\n**System information**\r\nPyGMT information:\r\n  version: v0.5.0\r\nSystem information:\r\n  python: 3.10.2 | packaged by conda-forge | (main, Mar  8 2022, 16:02:23) [Clang 11.1.0 ]\r\n  executable: ...\r\n  machine: ...\r\nDependency information:\r\n  numpy: 1.22.3\r\n  pandas: 1.4.1\r\n  xarray: 2022.3.0\r\n  netCDF4: 1.5.8\r\n  packaging: 21.3\r\n  ghostscript: 9.54.0\r\n  gmt: 6.3.0\r\nGMT library information:\r\n  binary dir: ...\r\n  cores: 4\r\n  grid layout: rows\r\n  library path: ...\r\n  padding: 2\r\n  plugin dir: ...\r\n  share dir: ...\r\n  version: 6.3.0\r\n\r\n```\r\nPASTE THE OUTPUT HERE\r\n```\r\n<img width=\"457\" alt=\"Schermafbeelding 2022-04-11 om 14 52 33\" src=\"https://user-images.githubusercontent.com/101344020/162770501-842f62c2-ba2b-46e5-bd1b-3cfe4d42e286.png\">\r\n\r\n<img width=\"523\" alt=\"Schermafbeelding 2022-04-11 om 14 52 15\" src=\"https://user-images.githubusercontent.com/101344020/162770474-4663765c-10df-4646-bb34-d4c1f13fd8b0.png\">\r\n\r\n",
    "closed_at": "2022-04-12T09:37:56Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/101344020?v=4",
        "events_url": "https://api.github.com/users/kiyoomogi/events{/privacy}",
        "followers_url": "https://api.github.com/users/kiyoomogi/followers",
        "following_url": "https://api.github.com/users/kiyoomogi/following{/other_user}",
        "gists_url": "https://api.github.com/users/kiyoomogi/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/kiyoomogi",
        "id": 101344020,
        "login": "kiyoomogi",
        "node_id": "U_kgDOBgpjFA",
        "organizations_url": "https://api.github.com/users/kiyoomogi/orgs",
        "received_events_url": "https://api.github.com/users/kiyoomogi/received_events",
        "repos_url": "https://api.github.com/users/kiyoomogi/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/kiyoomogi/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kiyoomogi/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/kiyoomogi"
    },
    "comments": 9,
    "comments_content": [
        {
            "author_association": "MEMBER",
            "body": "> projection = None     #or \"M4i\"\r\n\r\nFrom what I see, `projection` is only used in your `grdimage` call, not in `blockmean`. So setting `projection` to `None` or `M4i` should NOT affect your `blockmean` output. Perhaps it's something wrong with the `grdimage` call?\r\n\r\nIt would be easier to help if you can share your data points with us.",
            "created_at": "2022-04-11T15:53:06Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1878#issuecomment-1095235106",
            "id": 1095235106,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878",
            "node_id": "IC_kwDOBRZfO85BR_Yi",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095235106/reactions"
            },
            "updated_at": "2022-04-11T15:53:06Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095235106",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hello @seisman\r\nAttached here is a csv file with the datapoints. \r\nIt is indeed strange that the projection call that is done after the blockmean calculation somehow affects the outhput. \r\n\r\n[insar_data.csv](https://github.com/GenericMappingTools/pygmt/files/8465778/insar_data.csv)\r\n",
            "created_at": "2022-04-11T15:58:36Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1878#issuecomment-1095241209",
            "id": 1095241209,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878",
            "node_id": "IC_kwDOBRZfO85BSA35",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095241209/reactions"
            },
            "updated_at": "2022-04-11T15:58:36Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095241209",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/101344020?v=4",
                "events_url": "https://api.github.com/users/kiyoomogi/events{/privacy}",
                "followers_url": "https://api.github.com/users/kiyoomogi/followers",
                "following_url": "https://api.github.com/users/kiyoomogi/following{/other_user}",
                "gists_url": "https://api.github.com/users/kiyoomogi/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/kiyoomogi",
                "id": 101344020,
                "login": "kiyoomogi",
                "node_id": "U_kgDOBgpjFA",
                "organizations_url": "https://api.github.com/users/kiyoomogi/orgs",
                "received_events_url": "https://api.github.com/users/kiyoomogi/received_events",
                "repos_url": "https://api.github.com/users/kiyoomogi/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/kiyoomogi/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kiyoomogi/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/kiyoomogi"
            }
        },
        {
            "author_association": "NONE",
            "body": "Adding `projection = \"M4i\"` in `grd = pygmt.xyz2grd(data=df, region=region, spacing=spacing,projection=\"M4i\")` also does not seem to fix the problem. ",
            "created_at": "2022-04-11T16:01:53Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1878#issuecomment-1095244930",
            "id": 1095244930,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878",
            "node_id": "IC_kwDOBRZfO85BSByC",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095244930/reactions"
            },
            "updated_at": "2022-04-11T16:01:53Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095244930",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/101344020?v=4",
                "events_url": "https://api.github.com/users/kiyoomogi/events{/privacy}",
                "followers_url": "https://api.github.com/users/kiyoomogi/followers",
                "following_url": "https://api.github.com/users/kiyoomogi/following{/other_user}",
                "gists_url": "https://api.github.com/users/kiyoomogi/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/kiyoomogi",
                "id": 101344020,
                "login": "kiyoomogi",
                "node_id": "U_kgDOBgpjFA",
                "organizations_url": "https://api.github.com/users/kiyoomogi/orgs",
                "received_events_url": "https://api.github.com/users/kiyoomogi/received_events",
                "repos_url": "https://api.github.com/users/kiyoomogi/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/kiyoomogi/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kiyoomogi/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/kiyoomogi"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "The CSV file you provided doesn't have the head information, so `pd.read_csv` reports the following error for me:\r\n```\r\nKeyError: \"None of [Index(['long', 'lat', 'displ'], dtype='object')] are in the [columns]\"\r\n```",
            "created_at": "2022-04-11T16:07:08Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1878#issuecomment-1095250719",
            "id": 1095250719,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878",
            "node_id": "IC_kwDOBRZfO85BSDMf",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095250719/reactions"
            },
            "updated_at": "2022-04-11T16:07:08Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095250719",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "NONE",
            "body": "It should be fixed now. Had to convert it from ascii to csv. \r\n\r\n[insar_data.csv](https://github.com/GenericMappingTools/pygmt/files/8465932/insar_data.csv)\r\n",
            "created_at": "2022-04-11T16:10:03Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1878#issuecomment-1095253951",
            "id": 1095253951,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878",
            "node_id": "IC_kwDOBRZfO85BSD-_",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095253951/reactions"
            },
            "updated_at": "2022-04-11T16:10:03Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095253951",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/101344020?v=4",
                "events_url": "https://api.github.com/users/kiyoomogi/events{/privacy}",
                "followers_url": "https://api.github.com/users/kiyoomogi/followers",
                "following_url": "https://api.github.com/users/kiyoomogi/following{/other_user}",
                "gists_url": "https://api.github.com/users/kiyoomogi/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/kiyoomogi",
                "id": 101344020,
                "login": "kiyoomogi",
                "node_id": "U_kgDOBgpjFA",
                "organizations_url": "https://api.github.com/users/kiyoomogi/orgs",
                "received_events_url": "https://api.github.com/users/kiyoomogi/received_events",
                "repos_url": "https://api.github.com/users/kiyoomogi/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/kiyoomogi/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kiyoomogi/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/kiyoomogi"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Setting `projection=\"M4i\"` gives me the following image, which looks correct to me:\r\n\r\n<img width=\"503\" alt=\"image\" src=\"https://user-images.githubusercontent.com/3974108/162784805-b4d7a982-8ec5-4868-a9e0-b7d98645e042.png\">\r\n",
            "created_at": "2022-04-11T16:16:05Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1878#issuecomment-1095260877",
            "id": 1095260877,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878",
            "node_id": "IC_kwDOBRZfO85BSFrN",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095260877/reactions"
            },
            "updated_at": "2022-04-11T16:16:05Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095260877",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I'm using GMT dev + PyGMT v0.6.1. It works well for me. However, if I use GMT 6.3.0 + PyGMT v0.6.1, I can reproduce your issue.\r\n\r\nI think it's an upstream GMT bug in GMT 6.3.0, which may have been fixed in the GMT master branch... ",
            "created_at": "2022-04-11T16:23:16Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1878#issuecomment-1095268504",
            "id": 1095268504,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878",
            "node_id": "IC_kwDOBRZfO85BSHiY",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095268504/reactions"
            },
            "updated_at": "2022-04-11T16:23:16Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095268504",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "If you want to install the GMT dev version, you can use the following command:\r\n```\r\n$ conda install -c conda-forge/label/dev gmt\r\n```\r\n\r\nPlease let me know if the GMT dev version works for you or not.",
            "created_at": "2022-04-12T01:26:26Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1878#issuecomment-1095776735",
            "id": 1095776735,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878",
            "node_id": "IC_kwDOBRZfO85BUDnf",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095776735/reactions"
            },
            "updated_at": "2022-04-12T01:26:26Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1095776735",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "NONE",
            "body": "@seisman I installed the GMT dev version and I can recreate the correct blockmean image that you previously showed. \r\nThanks a lot for the help! Glad to see this issue is fixed in the dev version. ",
            "created_at": "2022-04-12T09:37:56Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1878#issuecomment-1096453684",
            "id": 1096453684,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878",
            "node_id": "IC_kwDOBRZfO85BWo40",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 1,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1096453684/reactions"
            },
            "updated_at": "2022-04-12T09:37:56Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1096453684",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/101344020?v=4",
                "events_url": "https://api.github.com/users/kiyoomogi/events{/privacy}",
                "followers_url": "https://api.github.com/users/kiyoomogi/followers",
                "following_url": "https://api.github.com/users/kiyoomogi/following{/other_user}",
                "gists_url": "https://api.github.com/users/kiyoomogi/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/kiyoomogi",
                "id": 101344020,
                "login": "kiyoomogi",
                "node_id": "U_kgDOBgpjFA",
                "organizations_url": "https://api.github.com/users/kiyoomogi/orgs",
                "received_events_url": "https://api.github.com/users/kiyoomogi/received_events",
                "repos_url": "https://api.github.com/users/kiyoomogi/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/kiyoomogi/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kiyoomogi/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/kiyoomogi"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878/comments",
    "created_at": "2022-04-11T15:19:16Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1878",
    "id": 1200129883,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        },
        {
            "color": "e8ff6b",
            "default": false,
            "description": "Bug or missing feature of upstream core GMT",
            "id": 2059525605,
            "name": "upstream",
            "node_id": "MDU6TGFiZWwyMDU5NTI1NjA1",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/upstream"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOBRZfO85HiIdb",
    "number": 1878,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878/timeline",
    "title": "BlockMean excludes datapoints with certain projections",
    "updated_at": "2022-04-12T09:43:02Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1878",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/101344020?v=4",
        "events_url": "https://api.github.com/users/kiyoomogi/events{/privacy}",
        "followers_url": "https://api.github.com/users/kiyoomogi/followers",
        "following_url": "https://api.github.com/users/kiyoomogi/following{/other_user}",
        "gists_url": "https://api.github.com/users/kiyoomogi/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/kiyoomogi",
        "id": 101344020,
        "login": "kiyoomogi",
        "node_id": "U_kgDOBgpjFA",
        "organizations_url": "https://api.github.com/users/kiyoomogi/orgs",
        "received_events_url": "https://api.github.com/users/kiyoomogi/received_events",
        "repos_url": "https://api.github.com/users/kiyoomogi/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/kiyoomogi/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kiyoomogi/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/kiyoomogi"
    }
}