{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "**Description of the problem**\r\n\r\n<!-- Please be as detailed as you can when describing an issue. The more information we have, the easier it will be for us to track this down. -->\r\n\r\nTrying to save or show a figure results in an error with ghostscript (gs) not found with a fresh conda install on Windows 10. This is with following the installation instructions at https://github.com/GenericMappingTools/pygmt/blob/v0.2.1/CONTRIBUTING.md#setting-up-your-environment. Note sure if there's something wrong with the conda `gmt` package at https://github.com/conda-forge/gmt-feedstock?\r\n\r\n**Full code that generated the error**\r\n\r\n```bash\r\npytest --verbose -x\r\n```\r\n\r\n**Full error message**\r\n\r\n```python-traceback\r\n(pygmt) PS H:\\github\\pygmt> pytest --verbose -x\r\n======================================== test session starts ========================================\r\nplatform win32 -- Python 3.8.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- C:\\Users\\username\\.conda\\envs\r\n\\pygmt\\python.exe\r\ncachedir: .pytest_cache\r\nMatplotlib: 3.3.4\r\nFreetype: 2.10.4\r\nrootdir: H:\\github\\pygmt, configfile: pyproject.toml\r\nplugins: cov-2.11.1, mpl-0.12\r\ncollected 0 items / 1 error\r\n\r\n============================================== ERRORS ===============================================\r\n________________________ ERROR collecting examples/gallery/coast/borders.py _________________________\r\nexamples\\gallery\\coast\\borders.py:25: in <module>\r\n    fig.show()\r\nH:\\github\\pygmt\\pygmt\\figure.py:277: in show\r\n    png = self._preview(\r\nH:\\github\\pygmt\\pygmt\\figure.py:349: in _preview\r\n    self.savefig(fname, dpi=dpi, **kwargs)\r\nH:\\github\\pygmt\\pygmt\\figure.py:232: in savefig\r\n    self.psconvert(prefix=prefix, fmt=fmt, crop=crop, **kwargs)\r\nH:\\github\\pygmt\\pygmt\\helpers\\decorators.py:267: in new_module\r\n    return module_func(*args, **kwargs)\r\nH:\\github\\pygmt\\pygmt\\helpers\\decorators.py:411: in new_module\r\n    return module_func(*args, **kwargs)\r\nH:\\github\\pygmt\\pygmt\\figure.py:173: in psconvert\r\n    lib.call_module(\"psconvert\", build_arg_string(kwargs))\r\nH:\\github\\pygmt\\pygmt\\clib\\session.py:503: in call_module\r\n    raise GMTCLibError(\r\nE   pygmt.exceptions.GMTCLibError: Module 'psconvert' failed with status code 78:\r\nE   psconvert [ERROR]: System call [@gswin64c -q -dNOSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pa\r\ngefill -dMaxBitmap=2147483647 -dUseFastColor=true \"C:/Users/username/.gmt/sessions/gmt_session.13356/gm\r\nt_1.ps-\" 2> \"C:/Users/username/.gmt/sessions/gmt_session.13356/psconvert_12992c.bb\"] returned error 1.\r\n------------------------------------------ Captured stderr ------------------------------------------\r\nThe system cannot find the path specified.\r\nThe system cannot find the path specified.\r\npsconvert [ERROR]: System call [@gswin64c -q -dNOSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefi\r\nll -dMaxBitmap=2147483647 -dUseFastColor=true \"C:/Users/username/.gmt/sessions/gmt_session.13356/gmt_1.\r\nps-\" 2> \"C:/Users/username/.gmt/sessions/gmt_session.13356/psconvert_12992c.bb\"] returned error 1.\r\n====================================== short test summary info ======================================\r\nERROR examples/gallery/coast/borders.py - pygmt.exceptions.GMTCLibError: Module 'psconvert' failed ...\r\n\r\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\r\n========================================= 1 error in 2.92s ==========================================\r\n```\r\n\r\nI've hit this issue a few times now since late last year, and had a friend who had a similar issue with not finding ghostscript last month, and I think the workaround he did was to manually download the ghostscript executable (gswin32.exe?) and place it at the right path. Not sure if it's a problem with our university's Windows system (we have funny network drives) or something with the `gmt` conda package not linking to `ghostscript` properly. This looks similar-ish to issue #393\r\n\r\nEdit: Might be an upstream `gmt` issue actually. Running pure GMT doesn't work either:\r\n\r\n```bash\r\ngmt basemap -R0/1/0/1 -JX1 -Baf -Vi -png map\r\n```\r\n\r\n```python-traceback\r\nbegin [INFORMATION]: Creating a workflow directory C:/Users/username/.gmt/sessions/gmt_session.13584\r\nbasemap [INFORMATION]: Constructing the basemap\r\nbasemap [INFORMATION]: Auto-frame interval for x-axis (item 0): a0.2f0.1\r\nbasemap [INFORMATION]: Auto-frame interval for y-axis (item 0): a0.2f0.1\r\nbasemap [INFORMATION]: Map scale is 0.001 km per cm or 1:100.\r\nend [INFORMATION]: Process GMT figure queue: 1 figures found\r\nend [INFORMATION]: Processing GMT figure #0 [map png ]\r\nThe system cannot find the path specified.\r\npsconvert [INFORMATION]: Processing C:/Users/username/.gmt/sessions/gmt_session.13584/gmt_0.ps-...\r\npsconvert [INFORMATION]: Find HiResBoundingBox ...\r\nThe system cannot find the path specified.\r\npsconvert [ERROR]: System call [@\"C:/Users/username/.conda/envs/pygmt/Library/bin/gswin64c.exe\" -q -dNOSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true \"C:/Users/username/.gmt/sessions/gmt_session.13584/gmt_0.ps-\" 2> \"C:/Users/username/.gmt/sessions/gmt_session.13584/psconvert_12268c.bb\"] returned error 1.\r\nend [ERROR]: Failed to call psconvert\r\nend [ERROR]: gmtinit_process_figures returned error 78\r\nend [INFORMATION]: Destroying the current workflow directory C:/Users/username/.gmt/sessions/gmt_session.13584\r\nbasemap [ERROR]: Unable to call module end for a one-liner plot.\r\n```\r\n\r\n**System information**\r\n\r\nPlease paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`:\r\n\r\n```\r\nPyGMT information:\r\n  version: v0.2.2.dev90+g8e2b3691\r\nSystem information:\r\n  python: 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 22:54:47) [MSC v.1916 64 bit (AMD64)]\r\n  executable: C:\\Users\\username\\.conda\\envs\\pygmt\\python.exe\r\n  machine: Windows-10-10.0.16299-SP0\r\nDependency information:\r\n  numpy: 1.19.5\r\n  pandas: 1.2.1\r\n  xarray: 0.16.2\r\n  netCDF4: 1.5.5.1\r\n  packaging: 20.8\r\n  ghostscript: 9.53.3\r\n  gmt: 6.1.1\r\nGMT library information:\r\n  binary dir: C:/Users/username/.conda/envs/pygmt\r\n  cores: 6\r\n  grid layout: rows\r\n  library path: C:/Users/username/.conda/envs/pygmt/Library/bin/gmt.dll\r\n  padding: 2\r\n  plugin dir: C:/Users/username/.conda/envs/pygmt/Library/bin/gmt_plugins\r\n  share dir: C:/Users/username/.conda/envs/pygmt/Library/share/gmt\r\n  version: 6.1.1\r\n```\r\n",
    "closed_at": "2021-02-20T23:32:54Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
        "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
        "followers_url": "https://api.github.com/users/weiji14/followers",
        "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
        "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/weiji14",
        "id": 23487320,
        "login": "weiji14",
        "node_id": "MDQ6VXNlcjIzNDg3MzIw",
        "organizations_url": "https://api.github.com/users/weiji14/orgs",
        "received_events_url": "https://api.github.com/users/weiji14/received_events",
        "repos_url": "https://api.github.com/users/weiji14/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/weiji14"
    },
    "comments": 7,
    "comments_content": [
        {
            "author_association": "MEMBER",
            "body": "Are you using a 32 bit Windows? \r\n\r\nCan you check if c:/Users/username/.conda/envs/pygmt/Library/bin/gswin64c.exe or c:/Users/username/.conda/envs/pygmt/Library/bin/gswin32c.exe exist?\r\n",
            "created_at": "2021-01-31T23:36:46Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/829#issuecomment-770472344",
            "id": 770472344,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/829",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MDQ3MjM0NA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/770472344/reactions"
            },
            "updated_at": "2021-01-31T23:36:46Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/770472344",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I'm on 64-bit Windows, and yes, both files exist and I can open them fine, so not sure why GMT isn't finding them\r\n\r\n```\r\n(pygmt) PS H:\\github\\pygmt> ls C:\\Users\\username\\.conda\\envs\\pygmt\\Library\\bin\\gswin*\r\n\r\n    Directory: C:\\Users\\username\\.conda\\envs\\pygmt\\Library\\bin\r\n\r\n\r\nMode                LastWriteTime         Length Name\r\n----                -------------         ------ ----\r\n-a----        9/11/2020  10:46 AM         102912 gswin64.exe\r\n-a----        9/11/2020  10:46 AM          92672 gswin64c.exe\r\n```",
            "created_at": "2021-01-31T23:57:47Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/829#issuecomment-770475748",
            "id": 770475748,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/829",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3MDQ3NTc0OA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/770475748/reactions"
            },
            "updated_at": "2021-01-31T23:57:47Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/770475748",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@weiji14 Perhaps you can try to install the GMT dev version instead? ",
            "created_at": "2021-02-03T22:39:52Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/829#issuecomment-772875767",
            "id": 772875767,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/829",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3Mjg3NTc2Nw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772875767/reactions"
            },
            "updated_at": "2021-02-03T22:39:52Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772875767",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> something with the `gmt` conda package not linking to `ghostscript` properly.\r\n\r\n`gmt` is not linked to `ghostscript`. It simply tries to search for `ghostscript` in Windows' registry or `gswin64c` in **PATH**.\r\n\r\nOne of the workarounds may be installing Ghostscript using the official installer, which updates the Windows registry.",
            "created_at": "2021-02-03T22:44:13Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/829#issuecomment-772877778",
            "id": 772877778,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/829",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3Mjg3Nzc3OA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772877778/reactions"
            },
            "updated_at": "2021-02-03T22:44:33Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772877778",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> `gmt` is not linked to `ghostscript`. It simply tries to search for `ghostscript` in Windows' registry or `gswin64c` in **PATH**.\r\n> \r\n> One of the workarounds may be installing Ghostscript using the official installer, which updates the Windows registry.\r\n\r\nHaven't got admin permissions on my university Windows system so changing the registry is not possible. But I'll try and install the dev version (i.e. `conda install -c conda-forge/label/dev gmt`) and see if it works.\r\n\r\nEdit: Nope, using GMT 6.2.0_e1b6a15_2021.02.02 still gives an error with using gswin64c.exe",
            "created_at": "2021-02-03T22:55:02Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/829#issuecomment-772882817",
            "id": 772882817,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/829",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc3Mjg4MjgxNw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772882817/reactions"
            },
            "updated_at": "2021-02-04T00:14:46Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/772882817",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "This is not a PyGMT issue, and all PyGMT tests work well on Windows. \r\n\r\nClose it? @weiji14 ",
            "created_at": "2021-02-20T22:17:31Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/829#issuecomment-782757842",
            "id": 782757842,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/829",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4Mjc1Nzg0Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/782757842/reactions"
            },
            "updated_at": "2021-02-20T22:17:31Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/782757842",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Ok, haven't had time to reproduce this properly. I'll close for now.",
            "created_at": "2021-02-20T23:32:54Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/829#issuecomment-782765519",
            "id": 782765519,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/829",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4Mjc2NTUxOQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/782765519/reactions"
            },
            "updated_at": "2021-02-20T23:32:54Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/782765519",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/829/comments",
    "created_at": "2021-01-31T23:08:03Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/829/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/829",
    "id": 797836202,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/829/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU3OTc4MzYyMDI=",
    "number": 829,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/829/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/829/timeline",
    "title": "Error with psconvert finding gswin64",
    "updated_at": "2021-02-20T23:32:55Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/829",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
        "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
        "followers_url": "https://api.github.com/users/weiji14/followers",
        "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
        "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/weiji14",
        "id": 23487320,
        "login": "weiji14",
        "node_id": "MDQ6VXNlcjIzNDg3MzIw",
        "organizations_url": "https://api.github.com/users/weiji14/orgs",
        "received_events_url": "https://api.github.com/users/weiji14/received_events",
        "repos_url": "https://api.github.com/users/weiji14/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/weiji14"
    }
}