{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "**Description of the problem**\r\n\r\n<!-- Please be as detailed as you can when describing an issue. The more information we have, the easier it will be for us to track this down. -->\r\nProblem with one of the GMT libraries on a fresh install of pygmt in a new conda env. \r\n\r\n```python\r\nconda create --name pygmt_test\r\nconda activate pygmt_test\r\nmamba install --channel conda-forge pygmt\r\npython\r\nimport pygmt\r\n```\r\n\r\n**Full error message**\r\n\r\n```\r\n>>> import pygmt\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/Users/jeremym/miniconda3/envs/pygmt_test/lib/python3.10/site-packages/pygmt/__init__.py\", line 71, in <module>\r\n    _begin()\r\n  File \"/Users/jeremym/miniconda3/envs/pygmt_test/lib/python3.10/site-packages/pygmt/session_management.py\", line 16, in begin\r\n    with Session() as lib:\r\n  File \"/Users/jeremym/miniconda3/envs/pygmt_test/lib/python3.10/site-packages/pygmt/clib/session.py\", line 183, in __enter__\r\n    self.create(\"pygmt-session\")\r\n  File \"/Users/jeremym/miniconda3/envs/pygmt_test/lib/python3.10/site-packages/pygmt/clib/session.py\", line 330, in create\r\n    c_create_session = self.get_libgmt_func(\r\n  File \"/Users/jeremym/miniconda3/envs/pygmt_test/lib/python3.10/site-packages/pygmt/clib/session.py\", line 282, in get_libgmt_func\r\n    self._libgmt = load_libgmt()\r\n  File \"/Users/jeremym/miniconda3/envs/pygmt_test/lib/python3.10/site-packages/pygmt/clib/loading.py\", line 59, in load_libgmt\r\n    raise GMTCLibNotFoundError(\"\\n\".join(error_msg))\r\npygmt.exceptions.GMTCLibNotFoundError: Error loading GMT shared library at '/Users/jeremym/miniconda3/envs/pygmt_test/lib/libgmt.dylib'.\r\ndlopen(/Users/jeremym/miniconda3/envs/pygmt_test/lib/libgmt.dylib, 0x0006): Symbol not found: _ZSTD_compressBound\r\n  Referenced from: /Users/jeremym/miniconda3/envs/pygmt_test/lib/libgdal.30.dylib\r\n  Expected in: /Users/jeremym/miniconda3/envs/pygmt_test/lib/libblosc.1.21.1.dylib\r\nError loading GMT shared library at 'libgmt.dylib'.\r\ndlopen(libgmt.dylib, 0x0006): Symbol not found: _ZSTD_compressBound\r\n  Referenced from: /Users/jeremym/miniconda3/envs/pygmt_test/lib/libgdal.30.dylib\r\n  Expected in: /Users/jeremym/miniconda3/envs/pygmt_test/lib/libblosc.1.21.1.dylib\r\n```\r\n\r\n**System information**\r\nThis command: `python -c \"import pygmt; pygmt.show_versions()\"` doesn't work due to the above error. `sys.version_info` gives the following:\r\n```\r\nsys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)\r\n```\r\nand platform.platform() gives: \r\n```\r\n'macOS-12.3.1-x86_64-i386-64bit'\r\n```",
    "closed_at": "2022-05-11T12:00:30Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    },
    "comments": 5,
    "comments_content": [
        {
            "author_association": "NONE",
            "body": "\ud83d\udc4b Thanks for opening your first issue here! Please make sure you filled out the template with as much detail as possible. You might also want to take a look at our [contributing guidelines](https://github.com/GenericMappingTools/pygmt/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/GenericMappingTools/pygmt/blob/main/CODE_OF_CONDUCT.md).\n",
            "created_at": "2022-05-10T16:35:46Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1923#issuecomment-1122625910",
            "id": 1122625910,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1923",
            "node_id": "IC_kwDOBRZfO85C6el2",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1122625910/reactions"
            },
            "updated_at": "2022-05-10T16:35:46Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1122625910",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/in/4141?v=4",
                "events_url": "https://api.github.com/users/welcome%5Bbot%5D/events{/privacy}",
                "followers_url": "https://api.github.com/users/welcome%5Bbot%5D/followers",
                "following_url": "https://api.github.com/users/welcome%5Bbot%5D/following{/other_user}",
                "gists_url": "https://api.github.com/users/welcome%5Bbot%5D/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/apps/welcome",
                "id": 30606887,
                "login": "welcome[bot]",
                "node_id": "MDM6Qm90MzA2MDY4ODc=",
                "organizations_url": "https://api.github.com/users/welcome%5Bbot%5D/orgs",
                "received_events_url": "https://api.github.com/users/welcome%5Bbot%5D/received_events",
                "repos_url": "https://api.github.com/users/welcome%5Bbot%5D/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/welcome%5Bbot%5D/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/welcome%5Bbot%5D/subscriptions",
                "type": "Bot",
                "url": "https://api.github.com/users/welcome%5Bbot%5D"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Hi @jlmaurer, thanks for the bug report. We're aware of the issue, and it seems to be a problem on conda-forge due to `blosc` (which `gdal` depends on) no longer packaging ZSTD, see https://github.com/conda-forge/blosc-feedstock/pull/53#issuecomment-1122080567. Hopefully this will get sorted out in the next day or so.",
            "created_at": "2022-05-10T17:03:32Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1923#issuecomment-1122651789",
            "id": 1122651789,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1923",
            "node_id": "IC_kwDOBRZfO85C6k6N",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1122651789/reactions"
            },
            "updated_at": "2022-05-10T17:03:32Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1122651789",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "As a workaround, could you try `mamba install --channel conda-forge pygmt blosc=1.21.0` and see if it works? Sorry that I can't test this, don't have a mac with me.",
            "created_at": "2022-05-10T17:22:11Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1923#issuecomment-1122668963",
            "id": 1122668963,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1923",
            "node_id": "IC_kwDOBRZfO85C6pGj",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1122668963/reactions"
            },
            "updated_at": "2022-05-10T17:22:11Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1122668963",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "NONE",
            "body": "@weiji14 that did the trick! Thanks",
            "created_at": "2022-05-10T17:51:35Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1923#issuecomment-1122696542",
            "id": 1122696542,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1923",
            "node_id": "IC_kwDOBRZfO85C6v1e",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1122696542/reactions"
            },
            "updated_at": "2022-05-10T17:51:35Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1122696542",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/22203981?v=4",
                "events_url": "https://api.github.com/users/jlmaurer/events{/privacy}",
                "followers_url": "https://api.github.com/users/jlmaurer/followers",
                "following_url": "https://api.github.com/users/jlmaurer/following{/other_user}",
                "gists_url": "https://api.github.com/users/jlmaurer/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jlmaurer",
                "id": 22203981,
                "login": "jlmaurer",
                "node_id": "MDQ6VXNlcjIyMjAzOTgx",
                "organizations_url": "https://api.github.com/users/jlmaurer/orgs",
                "received_events_url": "https://api.github.com/users/jlmaurer/received_events",
                "repos_url": "https://api.github.com/users/jlmaurer/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jlmaurer/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jlmaurer/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jlmaurer"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "The macOS CI works again. I think the upstream issue has been fixed.",
            "created_at": "2022-05-11T12:00:30Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1923#issuecomment-1123657493",
            "id": 1123657493,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1923",
            "node_id": "IC_kwDOBRZfO85C-acV",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1123657493/reactions"
            },
            "updated_at": "2022-05-11T12:00:30Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/1123657493",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1923/comments",
    "created_at": "2022-05-10T16:35:44Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1923/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1923",
    "id": 1231418698,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        },
        {
            "color": "e8ff6b",
            "default": false,
            "description": "Bug or missing feature of upstream core GMT",
            "id": 2059525605,
            "name": "upstream",
            "node_id": "MDU6TGFiZWwyMDU5NTI1NjA1",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/upstream"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1923/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": "2022-07-05T13:19:49Z",
        "closed_issues": 100,
        "created_at": "2021-11-06T22:12:34Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
            "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
            "followers_url": "https://api.github.com/users/weiji14/followers",
            "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
            "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/weiji14",
            "id": 23487320,
            "login": "weiji14",
            "node_id": "MDQ6VXNlcjIzNDg3MzIw",
            "organizations_url": "https://api.github.com/users/weiji14/orgs",
            "received_events_url": "https://api.github.com/users/weiji14/received_events",
            "repos_url": "https://api.github.com/users/weiji14/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/weiji14"
        },
        "description": null,
        "due_on": null,
        "html_url": "https://github.com/GenericMappingTools/pygmt/milestone/12",
        "id": 7333793,
        "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/12/labels",
        "node_id": "MI_kwDOBRZfO84Ab-eh",
        "number": 12,
        "open_issues": 0,
        "state": "closed",
        "title": "0.7.0",
        "updated_at": "2022-07-05T13:19:49Z",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/12"
    },
    "node_id": "I_kwDOBRZfO85JZfVK",
    "number": 1923,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1923/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1923/timeline",
    "title": "Error loading GMT shared library at 'libgmt.dylib'",
    "updated_at": "2022-05-11T12:00:31Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1923",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/22203981?v=4",
        "events_url": "https://api.github.com/users/jlmaurer/events{/privacy}",
        "followers_url": "https://api.github.com/users/jlmaurer/followers",
        "following_url": "https://api.github.com/users/jlmaurer/following{/other_user}",
        "gists_url": "https://api.github.com/users/jlmaurer/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/jlmaurer",
        "id": 22203981,
        "login": "jlmaurer",
        "node_id": "MDQ6VXNlcjIyMjAzOTgx",
        "organizations_url": "https://api.github.com/users/jlmaurer/orgs",
        "received_events_url": "https://api.github.com/users/jlmaurer/received_events",
        "repos_url": "https://api.github.com/users/jlmaurer/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/jlmaurer/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jlmaurer/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/jlmaurer"
    }
}