{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "**Description of the problem**\r\n\r\n<!-- Please be as detailed as you can when describing an issue. The more information we have, the easier it will be for us to track this down. -->\r\n\r\n**Full code that generated the error**\r\n\r\n```python\r\nimport pygmt\r\nimport pandas as pd\r\nimport numpy as np\r\n\r\ntable = pd.read_csv(\"https://raw.githubusercontent.com/GenericMappingTools/pygmt/master/pygmt/tests/data/points.txt\", sep=\" \", header=None)\r\n\r\nfig = pygmt.Figure()\r\nfig.histogram(table[0], pen=\"1p\", series=[0, 90, 10], frame=True)             # Fail\r\n#fig.histogram(np.array(table[0]), pen=\"1p\", series=[0, 90, 10], frame=True)  # Pass\r\nfig.show()\r\n```\r\nI have to convert `table[0]` to a numpy array to make it work.\r\n\r\n**Full error message**\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"test.py\", line 8, in <module>\r\n    fig.histogram(table[0], pen=\"1p\", series=[0, 90, 10], frame=True)\r\n  File \"pygmt/pygmt/helpers/decorators.py\", line 297, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"pygmt/pygmt/helpers/decorators.py\", line 438, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"pygmt/pygmt/src/histogram.py\", line 57, in histogram\r\n    with file_context as infile:\r\n  File \"lib/python3.8/contextlib.py\", line 113, in __enter__\r\n    return next(self.gen)\r\n  File \"pygmt/pygmt/clib/session.py\", line 1159, in virtualfile_from_vectors\r\n    rows = len(arrays[0])\r\nTypeError: len() of unsized object\r\n```\r\n\r\n**System information**\r\n\r\nPlease paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`:\r\n\r\n```\r\nPyGMT information:\r\n  version: v0.3.2.dev82+g82ebbbc4.d20210412\r\nSystem information:\r\n  python: 3.8.5 (default, Sep  4 2020, 02:22:02)  [Clang 10.0.0 ]\r\n  executable: /Users/XXX/.miniconda/bin/python\r\n  machine: macOS-10.16-x86_64-i386-64bit\r\nDependency information:\r\n  numpy: 1.20.1\r\n  pandas: 1.2.3\r\n  xarray: 0.17.0\r\n  netCDF4: 1.5.6\r\n  packaging: 20.9\r\n  ghostscript: 9.53.3\r\n  gmt: 6.2.0_522a350_2021.04.29\r\nGMT library information:\r\n  binary dir: /Users/XXX/.miniconda/bin\r\n  cores: 8\r\n  grid layout: rows\r\n  library path: /Users/XXX/opt/GMT-master/lib/libgmt.dylib\r\n  padding: 2\r\n  plugin dir: /Users/XXX/opt/GMT-master/lib/gmt/plugins\r\n  share dir: /Users/XXX/opt/GMT-master/share\r\n  version: 6.2.0\r\n```\r\n",
    "closed_at": "2021-06-20T02:05:03Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
        "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
        "followers_url": "https://api.github.com/users/weiji14/followers",
        "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
        "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/weiji14",
        "id": 23487320,
        "login": "weiji14",
        "node_id": "MDQ6VXNlcjIzNDg3MzIw",
        "organizations_url": "https://api.github.com/users/weiji14/orgs",
        "received_events_url": "https://api.github.com/users/weiji14/received_events",
        "repos_url": "https://api.github.com/users/weiji14/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/weiji14"
    },
    "comments": 1,
    "comments_content": [
        {
            "author_association": "MEMBER",
            "body": "Good catch, this isn't a problem restricted to just `histogram` though. I've stepped through the logic in `pygmt/clib/session.py` and believe it's a problem with the `vectors_to_arrays` function not handling a 1D `pandas.Series` properly, specifically this line:\r\n\r\nhttps://github.com/GenericMappingTools/pygmt/blob/d2cb8b953f08478666e3d3e3dda302a680679c17/pygmt/clib/conversion.py#L161\r\n\r\nThe list comprehension would loop through all the rows in the `pandas.Series`, when it should just treat the entire `pandas.Series` as a single array. I.e. `arrays = vectors_to_arrays(vectors)` produces this (wrong):\r\n\r\n```\r\n[array(43.4847),\r\n array(22.331),\r\n array(40.8023),\r\n array(49.876),\r\n array(60.6897),\r\n array(27.779),\r\n array(40.3582),\r\n array(18.9422),\r\n array(20.7545),\r\n array(19.8565),\r\n array(19.9855),\r\n array(46.4844),\r\n array(43.2328),\r\n array(59.3526),\r\n array(16.7597),\r\n array(32.3278),\r\n array(11.5309),\r\n array(61.7074),\r\n array(28.1125),\r\n array(47.8333)]\r\n```\r\n\r\nwhen it should actually produce this (correct):\r\n\r\n```\r\n[array([43.4847, 22.331 , 40.8023, 49.876 , 60.6897, 27.779 , 40.3582,\r\n        18.9422, 20.7545, 19.8565, 19.9855, 46.4844, 43.2328, 59.3526,\r\n        16.7597, 32.3278, 11.5309, 61.7074, 28.1125, 47.8333])]\r\n```\r\nand this is why `rows = len(arrays[0])` produces the `TypeError: len() of unsized object`, because it is only picking up `array(43.4847)` instead of `array(([43.4847, 22.331 ,...,])`\r\n\r\nThis may or may not be a duplicate of #1132 actually, since a `pandas.Series` is basically a 1D array, whereas we expect a 2D `pandas.DataFrame` array input into the `table` parameter (1D `numpy.array` objects are treated differently). But it's helpful to have the example test case above to debug the situation :smile:\r\n\r\n**Edit**: Actually there's probably several solutions to fix this bug, another way is to refactor the `virtualfile_from_data` function to handle `pandas.Series` objects properly since we're thinking of it already at https://github.com/GenericMappingTools/pygmt/pull/990#discussion_r587040494. Will do a bit more testing.",
            "created_at": "2021-05-02T22:44:12Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1253#issuecomment-830918752",
            "id": 830918752,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1253",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgzMDkxODc1Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/830918752/reactions"
            },
            "updated_at": "2021-05-02T23:12:23Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/830918752",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1253/comments",
    "created_at": "2021-05-02T14:59:33Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1253/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1253",
    "id": 873963269,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1253/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": "2021-06-21T14:49:45Z",
        "closed_issues": 244,
        "created_at": "2020-11-21T04:47:19Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
            "events_url": "https://api.github.com/users/seisman/events{/privacy}",
            "followers_url": "https://api.github.com/users/seisman/followers",
            "following_url": "https://api.github.com/users/seisman/following{/other_user}",
            "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/seisman",
            "id": 3974108,
            "login": "seisman",
            "node_id": "MDQ6VXNlcjM5NzQxMDg=",
            "organizations_url": "https://api.github.com/users/seisman/orgs",
            "received_events_url": "https://api.github.com/users/seisman/received_events",
            "repos_url": "https://api.github.com/users/seisman/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/seisman"
        },
        "description": "",
        "due_on": "2021-06-20T07:00:00Z",
        "html_url": "https://github.com/GenericMappingTools/pygmt/milestone/6",
        "id": 6133205,
        "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/6/labels",
        "node_id": "MDk6TWlsZXN0b25lNjEzMzIwNQ==",
        "number": 6,
        "open_issues": 0,
        "state": "closed",
        "title": "0.4.0",
        "updated_at": "2021-11-03T23:29:33Z",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/6"
    },
    "node_id": "MDU6SXNzdWU4NzM5NjMyNjk=",
    "number": 1253,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1253/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1253/timeline",
    "title": "Histogram doesn't work for pandas.Series",
    "updated_at": "2021-06-21T00:46:02Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1253",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    }
}