{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "**Description of the problem**\r\n\r\nload_earth_relief() is not working as intended, due to an error with grdcut mentioning that \"remote download is currently deactivated\". When trying to resolve this issue myself, I was looking into the deprecated GMT_AUTO_DOWNLOAD setting, but my attempts at changing GMT_DATA_UPDATE_INTERVAL does not resolve anything. While the full code I provided below is my own, the examples from the load_earth_relief documentation produce the same error as well. \r\n\r\n**Full code that generated the error**\r\n\r\n```python\r\nimport pygmt\r\nregion = [-119.25, -118.95, 37.525, 37.725]\r\ngrid = pygmt.datasets.load_earth_relief(resolution=\"01s\", region=region)\r\n```\r\n\r\n**Full error message**\r\n\r\n```\r\ngrdcut [ERROR]: Remote download is currently deactivated\r\ngrdcut [ERROR]: Unable to obtain remote file @earth_relief_01s\r\nTraceback (most recent call last):\r\n  File \"/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\r\n    exec(code_obj, self.user_global_ns, self.user_ns)\r\n  File \"<ipython-input-2-b9311e363d7b>\", line 3, in <module>\r\n    grid = pygmt.datasets.load_earth_relief(resolution=\"01s\", region=region)\r\n  File \"/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/pygmt/helpers/decorators.py\", line 725, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/pygmt/datasets/earth_relief.py\", line 140, in load_earth_relief\r\n    grid = grdcut(f\"@{earth_relief_prefix}{resolution}{reg}\", region=region)\r\n  File \"/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/pygmt/helpers/decorators.py\", line 582, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/pygmt/helpers/decorators.py\", line 725, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/pygmt/src/grdcut.py\", line 99, in grdcut\r\n    lib.call_module(\"grdcut\", arg_str)\r\n  File \"/opt/miniconda3/envs/enhance_catalog/lib/python3.8/site-packages/pygmt/clib/session.py\", line 505, in call_module\r\n    raise GMTCLibError(\r\npygmt.exceptions.GMTCLibError: Module 'grdcut' failed with status code 72:\r\ngrdcut [ERROR]: Remote download is currently deactivated\r\ngrdcut [ERROR]: Unable to obtain remote file @earth_relief_01s\r\n```\r\n\r\n**System information**\r\n\r\nPlease paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`:\r\n\r\n```\r\nPyGMT information:\r\n  version: v0.4.1\r\nSystem information:\r\n  python: 3.8.12 | packaged by conda-forge | (default, Sep 29 2021, 19:44:33)  [Clang 11.1.0 ]\r\n  executable: /opt/miniconda3/envs/enhance_catalog/bin/python\r\n  machine: macOS-10.16-x86_64-i386-64bit\r\nDependency information:\r\n  numpy: 1.21.2\r\n  pandas: 1.3.2\r\n  xarray: 0.19.0\r\n  netCDF4: 1.5.7\r\n  packaging: 21.0\r\n  ghostscript: 9.54.0\r\n  gmt: 6.2.0\r\nGMT library information:\r\n  binary dir: /opt/miniconda3/envs/enhance_catalog/bin\r\n  cores: 8\r\n  grid layout: rows\r\n  library path: /opt/miniconda3/envs/enhance_catalog/lib/libgmt.dylib\r\n  padding: 2\r\n  plugin dir: /opt/miniconda3/envs/enhance_catalog/lib/gmt/plugins\r\n  share dir: /opt/miniconda3/envs/enhance_catalog/share/gmt\r\n  version: 6.2.0\r\n```\r\n",
    "closed_at": "2021-10-01T22:30:34Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/70110994?v=4",
        "events_url": "https://api.github.com/users/darren-tpk/events{/privacy}",
        "followers_url": "https://api.github.com/users/darren-tpk/followers",
        "following_url": "https://api.github.com/users/darren-tpk/following{/other_user}",
        "gists_url": "https://api.github.com/users/darren-tpk/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/darren-tpk",
        "id": 70110994,
        "login": "darren-tpk",
        "node_id": "MDQ6VXNlcjcwMTEwOTk0",
        "organizations_url": "https://api.github.com/users/darren-tpk/orgs",
        "received_events_url": "https://api.github.com/users/darren-tpk/received_events",
        "repos_url": "https://api.github.com/users/darren-tpk/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/darren-tpk/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/darren-tpk/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/darren-tpk"
    },
    "comments": 5,
    "comments_content": [
        {
            "author_association": "NONE",
            "body": "\ud83d\udc4b Thanks for opening your first issue here! Please make sure you filled out the template with as much detail as possible. You might also want to take a look at our [contributing guidelines](https://github.com/GenericMappingTools/pygmt/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/GenericMappingTools/pygmt/blob/main/CODE_OF_CONDUCT.md).\n",
            "created_at": "2021-10-01T22:01:40Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1556#issuecomment-932601651",
            "id": 932601651,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1556",
            "node_id": "IC_kwDOBRZfO843ll8z",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/932601651/reactions"
            },
            "updated_at": "2021-10-01T22:01:40Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/932601651",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/in/4141?v=4",
                "events_url": "https://api.github.com/users/welcome%5Bbot%5D/events{/privacy}",
                "followers_url": "https://api.github.com/users/welcome%5Bbot%5D/followers",
                "following_url": "https://api.github.com/users/welcome%5Bbot%5D/following{/other_user}",
                "gists_url": "https://api.github.com/users/welcome%5Bbot%5D/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/apps/welcome",
                "id": 30606887,
                "login": "welcome[bot]",
                "node_id": "MDM6Qm90MzA2MDY4ODc=",
                "organizations_url": "https://api.github.com/users/welcome%5Bbot%5D/orgs",
                "received_events_url": "https://api.github.com/users/welcome%5Bbot%5D/received_events",
                "repos_url": "https://api.github.com/users/welcome%5Bbot%5D/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/welcome%5Bbot%5D/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/welcome%5Bbot%5D/subscriptions",
                "type": "Bot",
                "url": "https://api.github.com/users/welcome%5Bbot%5D"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "We are experiencing an issue with the GMT server. In the meantime, you can use `pygmt.config(GMT_DATA_SERVER=\"https://oceania.generic-mapping-tools.org\")` to get your code to work:\r\n\r\n```\r\nimport pygmt\r\nregion = [-119.25, -118.95, 37.525, 37.725]\r\npygmt.config(GMT_DATA_SERVER=\"https://oceania.generic-mapping-tools.org\")\r\ngrid = pygmt.datasets.load_earth_relief(resolution=\"01s\", region=region)\r\n```",
            "created_at": "2021-10-01T22:07:19Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1556#issuecomment-932604745",
            "id": 932604745,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1556",
            "node_id": "IC_kwDOBRZfO843lmtJ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/932604745/reactions"
            },
            "updated_at": "2021-10-01T22:07:19Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/932604745",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Hi @darren-uaf, there are some issues with the GMT server currently, see https://github.com/GenericMappingTools/gmt/issues/5830. The current workaround would be to set [`GMT_DATA_SERVER`](https://docs.generic-mapping-tools.org/6.2/gmt.conf.html#term-GMT_DATA_SERVER) to use https like so:\r\n\r\n```python\r\nwith pygmt.config(\"GMT_DATA_SERVER\"=\"https://oceania.generic-mapping-tools.org\"):\r\n    grid = pygmt.datasets.load_earth_relief(resolution=\"01s\", region=region)\r\n```\r\n\r\nOr you can choose one of the other \"Data Server Mirrors\" at https://www.generic-mapping-tools.org/mirrors/. Let us know if it works.",
            "created_at": "2021-10-01T22:08:35Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1556#issuecomment-932605269",
            "id": 932605269,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1556",
            "node_id": "IC_kwDOBRZfO843lm1V",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/932605269/reactions"
            },
            "updated_at": "2021-10-01T22:08:57Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/932605269",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "NONE",
            "body": "@meghanrjones @weiji14 Thank you for your prompt responses. Sorry that I missed the other open issue, it didn't come up when I searched load_earth_relief(). Your suggestions fixed this issue, thanks!",
            "created_at": "2021-10-01T22:30:34Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1556#issuecomment-932613699",
            "id": 932613699,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1556",
            "node_id": "IC_kwDOBRZfO843lo5D",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/932613699/reactions"
            },
            "updated_at": "2021-10-01T22:30:34Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/932613699",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/70110994?v=4",
                "events_url": "https://api.github.com/users/darren-tpk/events{/privacy}",
                "followers_url": "https://api.github.com/users/darren-tpk/followers",
                "following_url": "https://api.github.com/users/darren-tpk/following{/other_user}",
                "gists_url": "https://api.github.com/users/darren-tpk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/darren-tpk",
                "id": 70110994,
                "login": "darren-tpk",
                "node_id": "MDQ6VXNlcjcwMTEwOTk0",
                "organizations_url": "https://api.github.com/users/darren-tpk/orgs",
                "received_events_url": "https://api.github.com/users/darren-tpk/received_events",
                "repos_url": "https://api.github.com/users/darren-tpk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/darren-tpk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/darren-tpk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/darren-tpk"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "The server issue has been fixed by RCF staff, so you can try re-running your script without the pygmt.config() setting. Please post if you run into any more issues.",
            "created_at": "2021-10-01T22:32:23Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1556#issuecomment-932614258",
            "id": 932614258,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1556",
            "node_id": "IC_kwDOBRZfO843lpBy",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/932614258/reactions"
            },
            "updated_at": "2021-10-01T22:32:23Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/932614258",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1556/comments",
    "created_at": "2021-10-01T22:01:39Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1556/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1556",
    "id": 1013795965,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1556/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOBRZfO848bUx9",
    "number": 1556,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1556/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1556/timeline",
    "title": "Remote download is deactivated, unable to obtain remote file for earth relief",
    "updated_at": "2021-10-01T22:32:23Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1556",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/70110994?v=4",
        "events_url": "https://api.github.com/users/darren-tpk/events{/privacy}",
        "followers_url": "https://api.github.com/users/darren-tpk/followers",
        "following_url": "https://api.github.com/users/darren-tpk/following{/other_user}",
        "gists_url": "https://api.github.com/users/darren-tpk/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/darren-tpk",
        "id": 70110994,
        "login": "darren-tpk",
        "node_id": "MDQ6VXNlcjcwMTEwOTk0",
        "organizations_url": "https://api.github.com/users/darren-tpk/orgs",
        "received_events_url": "https://api.github.com/users/darren-tpk/received_events",
        "repos_url": "https://api.github.com/users/darren-tpk/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/darren-tpk/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/darren-tpk/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/darren-tpk"
    }
}